### ISSUE TITLE
SeleniumLibrary 3.1.0 unit test do not work with Selenium 3.0.0 - 3.7.0.

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1069]
With Selenium 3.0.0 - 3.7.0 SeleniumLibrary 4 unit test do fail. I see this type of errors: 
```
======================================================================
ERROR: test_firefox_profile (keywords.test_webdrivercreator.WebDriverCreatorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/godtdd/workspace/SeleniumLibrary/utest/test/keywords/test_webdrivercreator.py", line 133, in test_firefox_profile
    driver = self.creator.create_firefox({}, None, '/profile/dir')
  File "/home/godtdd/workspace/SeleniumLibrary/utest/../src/SeleniumLibrary/keywords/webdrivertools.py", line 108, in create_firefox
    **self._geckodriver_log)
  File "/usr/local/lib/python2.7/dist-packages/mockito/mocking.py", line 86, in new_mocked_method
    self, method_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mockito/mocking.py", line 44, in remembered_invocation_builder
    return invoc(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 178, in __call__
    """ % (self, "\n    ".join(str(invoc) for invoc in stubbed_invocations)))
InvocationError: 
You called

        Firefox(log_path='/log/dir/geckodriver.log', firefox_profile=<Dummy id=140678508006480>, capabilities={'acceptInsecureCerts': True, 'browserName': 'firefox', 'marionette': True}),

which is not expected. Stubbed invocations are:

        Firefox(firefox_profile=<Dummy id=140678508006480>, capabilities={'acceptInsecureCerts': True, 'browserName': 'firefox', 'marionette': True})
    FirefoxProfile('/profile/dir')

(Set strict to False to bypass this check.)
```
With Selenium 2.53.6 or Selenium 3.8.0 or never, unit test do work. It looks like the SeleniumLibrary works fine, only the unit tests fail.

**Comment by aaltat** [comment]
I think we don't need to fix this because need for those Selenium versions is fading away. Therefore closing this issue.
