### ISSUE TITLE
ElementFinder can't raise correct exception if locator contains characters like ö ä å 

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1084]
When I have this: 
`| Click Element | id:äääääää | `
and element is not found. then this is seen:
```
Traceback (most recent call last):
  File "/home/godtdd/workspace/SeleniumLibrary/src/SeleniumLibrary/__init__.py", line 360, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "/home/godtdd/workspace/SeleniumLibrary/src/SeleniumLibrary/base/robotlibcore.py", line 102, in run_keyword
    return self.keywords[name](*args, **kwargs)
  File "/home/godtdd/workspace/SeleniumLibrary/src/SeleniumLibrary/keywords/element.py", line 464, in click_element
    self.find_element(locator).click()
  File "/home/godtdd/workspace/SeleniumLibrary/src/SeleniumLibrary/base/context.py", line 62, in find_element
    return self.element_finder.find(locator, tag, True, required, parent)
  File "/home/godtdd/workspace/SeleniumLibrary/src/SeleniumLibrary/locators/elementfinder.py", line 76, in find
    .format(element_type, locator))
```

**Comment by aaltat** [comment]
Fixed in #1085
