### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: chrome failed to start

### ISSUE THREAD

**Issue by r8w9a5k** [robotframework/SeleniumLibrary#1107]
Hello, I am getting this exception.
_selenium.common.exceptions.WebDriverException: Message: unknown error: chrome failed to start_

I have two identical computers, one can run selenium just fine and the second has this problem. I am on win10, 64bit, python v 3.6.5, chromedriver v 2.3.7 on both computers.

Full error:

```
Traceback (most recent call last):
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\.pyProjects\vcasdgas\exdasfgsal.py", line 11, in <module>
    browser = webdriver.Chrome()
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: chrome failed to start
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.16299 x86_64)
```

**Comment by aaltat** [comment]
The code in the issue does not look like a SeleniumLibrary keyword. Are you actually looking the Selenium issue tracker: https://github.com/SeleniumHQ/selenium/issues

**Comment by r8w9a5k** [comment]
@aaltat Thank you. I will try.
