### ISSUE TITLE
BadStatusLine: '': getting BadStatusLine: '' error on clicking log in link on ubuntu for fire fox browser 

### ISSUE THREAD

**Issue by pkgondi** [robotframework/SeleniumLibrary#1163]
BadStatusLine: '': getting BadStatusLine: '' error when automation scripts executes for  click link login  element on ubuntu os  for fire fox browser. 
works fine for google chrome browser on ubuntu
works fine on mac ios system for firefox and google chrome browsers

softwares versions installed on ubuntu system
geckodriver 0.21.0 
Mozilla Firefox 61.0.1
selenium (3.13.0)
robotframework-seleniumlibrary (3.1.1)
robotframework (3.0.4)

error message:

 | INFO | Clicking element '//a[.='Log In / Register']'. |  
-- | -- | -- | --

BadStatusLine: ''
--

please help on this 

trace logs mentioned below

Clicking link '//a[.='Tu Log In / Register']'. |  
-- | --
Traceback (most recent call last):
  File "<decorator-gen-82>", line 2, in click_link
  File "/usr/local/lib/python2.7/dist-packages/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Selenium2Library/keywords/_element.py", line 520, in click_link
    link = self._element_find(locator, True, True, tag='a')
  File "/usr/local/lib/python2.7/dist-packages/Selenium2Library/keywords/_element.py", line 688, in _element_find
    elements = self._element_finder.find(browser, locator, tag)
  File "/usr/local/lib/python2.7/dist-packages/Selenium2Library/locators/elementfinder.py", line 37, in find
    return strategy(browser, criteria, tag, constraints)
  File "/usr/local/lib/python2.7/dist-packages/Selenium2Library/locators/elementfinder.py", line 122, in _find_by_default
    return self._find_by_xpath(browser, criteria, tag, constraints)
  File "/usr/local/lib/python2.7/dist-packages/Selenium2Library/locators/elementfinder.py", line 79, in _find_by_xpath
    browser.find_elements_by_xpath(criteria),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 401, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 983, in find_elements
    'value': value})['value'] or []
  File "/usr/local/lib/python2.7/dist-packages/Selenium2Library/webdrivermonkeypatches.py", line 11, in execute
    result = self._base_execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 490, in _request
    resp = self._conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)

Thank you in advance

**Comment by aaltat** [comment]
The error comes from the communication between Selenium and the Geckodriver. Bad status line means that the Geckodriver did response something which the Python http library did not understand. Usually it means that something catastrophic did happen in the the browser or in the Geckodriver.

Usually updating or downgrading the Firefox, Geckodriver or Selenium to compatible versions will solve the problem.

But because this is more an support request, I will close the issue. For more support, please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support

**Comment by pkgondi** [comment]
working fine after downgraded geckodriver to geckodriver 0.20.1 from geckodriver 0.21.0 thank you for your support
Thank you Tatu Aalto for your help
