### ISSUE TITLE
When EventFiringWebDriver is enabled, setting selenium speed triggers exception

### ISSUE THREAD

**Issue by rasjani** [robotframework/SeleniumLibrary#1505]
## Steps to reproduce the issue

* use SeleniumTestability ;) for example to enable EventFiringWebDriver.
* call Set Selenium Speed 

## Error messages and additional information

'WebDriver' object has no attribute '_base_execute'

## Expected behavior and actual behavior

No exceptions should be thrown

**Comment by aaltat** [comment]
When I have this:
```
*** Settings ***
Library           SeleniumLibrary    event_firing_webdriver=${CURDIR}/MyListener.py

Event Firing Webdriver Set Selenium Speed
    ${speed}    Get Selenium Speed
    Set Selenium Speed    1.42
    [Teardown]    Set Selenium Speed    ${speed}
```
It actually works without errors. Need to install SeleniumTestability and see closed.

**Comment by aaltat** [comment]
When trying with SeleniumTestability plugin, I get different error which indicates error in the plugin. When I have this: 
```
*** Settings ***
Library           SeleniumLibrary    plugins=SeleniumTestability
```
Then I get this error:
```
 ERROR ] Error in file '/home/usernameworkspace/SeleniumLibrary/atest/acceptance/2-event_firing_webdriver/event_firing_webdriver.robot': Initializing test library 'SeleniumLibrary' with arguments [ plugins=SeleniumTestability ] failed: TypeError: Level not an integer or a valid string: <function debug at 0x7f558e3ba400>
Traceback (most recent call last):
  File "/home/usernameworkspace/SeleniumLibrary/src/SeleniumLibrary/__init__.py", line 458, in __init__
    plugin_libs = self._parse_plugins(plugins)
  File "/home/username/workspace/SeleniumLibrary/src/SeleniumLibrary/__init__.py", line 587, in _parse_plugins
    **parsed_plugin.kw_args)
  File "/home/username/apps/selenium_testability/lib/python3.7/site-packages/SeleniumTestability/plugin.py", line 176, in __init__
    self.logger = get_logger("SeleniumTestability")
  File "/home/username/apps/selenium_testability/lib/python3.7/site-packages/SeleniumTestability/logger.py", line 28, in get_logger
    lgr.setLevel(set_to)  # type: ignore
  File "/usr/lib/python3.7/logging/__init__.py", line 1358, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib/python3.7/logging/__init__.py", line 195, in _checkLevel
    raise TypeError("Level not an integer or a valid string: %r" % level)
Acceptance.2-Event Firing Webdriver.Event Firing Webdriver
```
But the error comes from the plugin, not from SeleniumLibrary. @rasjani I would need example which demonstrates the problem and I can also run.

**Comment by rasjani** [comment]
Can’t reproduce anymore. It was present in few bug reports submitted to me but can’t reproduce those anymore locally
