### ISSUE TITLE
Opening IE browser is not possible in SeleniumLibrary 4.2.0

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1548]
When using Open Browser keyword with IE browser, keyword fails with error: `SessionNotCreatedException: Message: Unable to find a matching set of capabilities`. The full stack trace is: 
```
    Traceback (most recent call last):
  File "c:\python38\lib\site-packages\SeleniumLibrary\__init__.py", line 470, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "c:\python38\lib\site-packages\SeleniumLibrary\base\robotlibcore.py", line 103, in run_keyword
    return self.keywords[name](*args, **kwargs)
  File "c:\python38\lib\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 285, in open_browser
    return self._make_new_browser(url, browser, alias, remote_url,
  File "c:\python38\lib\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 298, in _make_new_browser
    driver = self._make_driver(browser, desired_capabilities,
  File "c:\python38\lib\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 669, in _make_driver
    driver = self._webdriver_creator.create_driver(
  File "c:\python38\lib\site-packages\SeleniumLibrary\keywords\webdrivertools\webdrivertools.py", line 77, in create_driver
    return creation_method(desired_capabilities, remote_url, options=options,
  File "c:\python38\lib\site-packages\SeleniumLibrary\keywords\webdrivertools\webdrivertools.py", line 203, in create_ie
    return webdriver.Ie(options=options, service_log_path=service_log_path, executable_path=executable_path,
  File "c:\python38\lib\site-packages\selenium\webdriver\ie\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "c:\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "c:\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "c:\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
```

The bug is in SelemiumLibrary, which tries to use `geckodriver` as browser driver for IE.

**Comment by pekkaklarck** [comment]
Some cross browser testing would probably be a good idea.

**Comment by aaltat** [comment]
Automatic cross browser testing is mostly done with unit test, but I should have run more manual tests with the 4.2 release.
