### ISSUE TITLE
Robot fails to run with the latest libraries installed

### ISSUE THREAD

**Issue by luismoyano** [robotframework/SeleniumLibrary#1684]
# For issues
## Prerequisites
- Using Python 3.8.5
- Using Robot Framework 3.2.2
- Using SeleniumLibrary 5.0.0
- Using chromedriver 88.0.4324

## Steps to reproduce the issue
Run any robot framework project with command `robot path/to/tests.robot`

## Error messages and additional information
```
[ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10aab8160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10aab8310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10aab8670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session
Personal Details Changes                                              | FAIL |
Setup failed:
MaxRetryError: HTTPConnectionPool(host='false', port=80): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10aab8610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

## Expected behavior and actual behavior

The suite fails to run, it doesn't even open the browser. I'd like to go back and try to find a setup that works, but now I'm not sure what I would need to install and these versions are the latest ones up to date.

I was expecting for the suite to run.

## Environment

Browser: Chrome 88
Browser driver: chromefriver 88
Operating System: Mac OS El Capitán
Libraries
- Using Python 3.8.5
- Using Robot Framework 3.2.2
- Using SeleniumLibrary 5.0.0
- Using chromedriver 88.0.4324

**Comment by aaltat** [comment]
No idea with these details. Could you run test with `--loglevel trace` set from command line and post the full stack trace from the log.html file.

**Comment by luismoyano** [comment]
Here it is!

```
Traceback (most recent call last):
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/SeleniumLibrary/__init__.py", line 492, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/robotlibcore.py", line 103, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/SeleniumLibrary/keywords/browsermanagement.py", line 292, in open_browser
    return self._make_new_browser(
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/SeleniumLibrary/keywords/browsermanagement.py", line 323, in _make_new_browser
    driver = self._make_driver(
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/SeleniumLibrary/keywords/browsermanagement.py", line 715, in _make_driver
    driver = self._webdriver_creator.create_driver(
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/SeleniumLibrary/keywords/webdrivertools/webdrivertools.py", line 91, in create_driver
    return creation_method(
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/SeleniumLibrary/keywords/webdrivertools/webdrivertools.py", line 145, in create_chrome
    return self._remote(desired_capabilities, remote_url, options=options)
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/SeleniumLibrary/keywords/webdrivertools/webdrivertools.py", line 461, in _remote
    return webdriver.Remote(
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 402, in _request
    resp = http.request(method, url, body=body, headers=headers)
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/luismoyano/.pyenv/versions/3.8.5/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
```

**Comment by aaltat** [comment]
Based on the stack trace it looks like you are using Selenium grid and Selenium can't connect to the grid. This looks environment problem, perhaps the grid is not running or something similar. In any case this is starting to look like support case and support is handled by community https://github.com/robotframework/SeleniumLibrary#community
