### ISSUE TITLE
Library Documentation Error with Robot Framework 4

### ISSUE THREAD

**Issue by bbartok76** [robotframework/SeleniumLibrary#1706]
I faced with the following error when I created a new installation with Python 3.9 & Robot Framework 4:

Error displaying documentation
Following exception has been thrown:
            Traceback (most recent call last):
              File "C:\Users\hubartob\AppData\Local\Temp\RobotTempDir14982430887361600969\robot_session_server.py", line 43, in inner
                result['result'] = func(*args, **kwargs)
              File "C:\Users\hubartob\AppData\Local\Temp\RobotTempDir14982430887361600969\robot_session_server.py", line 78, in inner
                return func(*args, **kwargs)
              File "C:\Users\hubartob\AppData\Local\Temp\RobotTempDir14982430887361600969\robot_session_server.py", line 417, in create_html_doc
                return red_libraries.create_html_doc(doc, format)
              File "C:\Users\hubartob\AppData\Local\Temp\RobotTempDir14982430887361600969\red_libraries.py", line 122, in create_html_doc
                from robot.libdocpkg.htmlwriter import DocToHtml
            ImportError: cannot import name 'DocToHtml' from 'robot.libdocpkg.htmlwriter' (c:\Python39\lib\site-packages\robot\libdocpkg\htmlwriter.py)

I checked the referenced robot\libdocpkg\htmlwriter.py and the new (4.0) version of this module doesn't contain the DocToHtml contrary to the older version I've used (3.2.2).

**Comment by bbartok76** [comment]
Please delete the issue if possible, I submitted it to the wrong project :)
