### ISSUE TITLE
IE: ocasional NoSuchElementException while locating elements

### ISSUE THREAD

**Issue by ombre42** [robotframework/SeleniumLibrary#173]
Update(6/25/2013): Newer versions of Se raising NoSuchElementException instead with message "Finding elements returned an unexpected error". Updating the title to reflect that.

When trying to find elements during a page load and possibly a DOM update, WebDriver sometimes raises a InvalidSelectiorException[sic] when the XPath is valid. This is problematic because it causes Wait Until Page Contains Element to fail. It is difficult to sync to a page load triggered by an AJAX call because the location, URL, and title may not necessarily change. One workaround is to use Wait Until Keyword Succeeds with Page Should Contain Element, but this has some drawbacks:
- Browser pop-ups (e.g. JavaScript errors) are hidden because WebDriver dismisses them on any method call and an exception is only raised once (UPDATE: desired capability unexpectedAlertBehaviour can change this behavior only for Selenium >= 2.25)
- Failures take the full timeout to fail

**Comment by ombre42** [comment]
This is the workaround we are using at our company. I am not suggesting this is the best solution, but it has worked for us. Similar to the fluent wait in Java, it allows you to set which exceptions you want to ignore. The only one that has been needed so far is InvalidSelectiorException. Since this is a monkey patch, it must be loaded before any instance of Selenium2Library is created.

```
import re
import time
import robot
from robot.api import logger
import selenium.common.exceptions as exceptions
from Selenium2Library import utils
from Selenium2Library.keywords.keywordgroup import KeywordGroup
from Selenium2Library.keywords import _WaitingKeywords


class SeleniumExceptionMatcher(object):

    def __init__(self, user_repr):
        exclass, _, regexp = user_repr.partition('|')
        if not hasattr(exceptions, exclass):
            raise ValueError("selenium.common.exceptions does not define %s" % exclass)
        self._exception = getattr(exceptions, exclass)
        if regexp:
            try:
                self._regexp = re.compile(regexp)
            except Exception, e:
                raise ValueError("Bad regular expression '%s': %s" % (regexp, e))
        else:
            self._regexp = None

    def matches(self, ex):
        if not isinstance(ex, self._exception):
            return False
        if self._regexp:
            if not self._regexp.search(ex.msg):
                logger.debug("Pattern '%s' not found in exception message '%s'" \
                             % (self._regexp.pattern, ex.msg))
                return False
        return True

    def user_repr(self):
        repr = self._exception.__name__
        if self._regexp:
            repr += '|' + self._regexp.pattern
        return repr


class _WaitingKeywordsMonkeyPatches(KeywordGroup):

    def __init__(self): # no init before patching
        # key:browser instance, value:SeleniumExceptionMatcher[]
        self._exception_matchers = {}

    def set_ignored_wait_exceptions(self, *exceptions):
        """Sets the exceptions to ignore while waiting.

        `exceptions` must be exception class names defined in 
        selenium.common.exceptions. The exceptions will be ignored by the Wait 
        Until * keywords in Selenium2Library for the _current_ browser 
        instance. For more control a regular expression can be appended to 
        the exception class after a pipe. When a regular expression is 
        specified, an instance will only be ignored if the exception message 
        matches the regular expression. The same exception can appear multiple 
        times. 

        Example:
        | @{old ignored}=                  | Set Ignored Wait Exceptions | InvalidSelectiorException | WebDriverException|modal |
        | Wait Until Page Contains Element | id=name                     |                           |                          |
        | Set Ignored Wait Exceptions      | @{old ignored}              | # restore previous        |                          |
        """
        browser = self._current_browser()
        old_ex_matchers = self._exception_matchers.get(browser) or []
        ex_matchers = [SeleniumExceptionMatcher(ex) for ex in exceptions]
        self._exception_matchers[browser] = ex_matchers
        return [em.user_repr() for em in old_ex_matchers]

    def _wait_until_ignoring(self, timeout, error, function, *args):
        timeout = robot.utils.timestr_to_secs(timeout) if timeout is not None else self._timeout_in_secs
        error = error.replace('<TIMEOUT>', robot.utils.secs_to_timestr(timeout))
        maxtime = time.time() + timeout
        matchers = self._exception_matchers.get(self._current_browser()) or []
        ignored_names = []
        while True:
            try:
                if function(*args): return
            except exceptions.WebDriverException, e:
                ignored = False
                for ex_matcher in matchers:
                    if ex_matcher.matches(e):
                        ignored = True
                        name = e.__class__.__name__
                        # log warn level event at most once per exception type per wait
                        if name not in ignored_names:
                            ignored_names.append(name)
                            self._info("Ignored during wait: %s: %s" % (name, e))
                        else:
                            self._debug("Ignored during wait: %s: %s" % (name, e))
                        break
                if not ignored:
                    raise
            if time.time() > maxtime:
                raise AssertionError(error)
            time.sleep(0.2)

    _WaitingKeywords.__init__ = __init__
    _WaitingKeywords.set_ignored_wait_exceptions = set_ignored_wait_exceptions
    _WaitingKeywords._wait_until = _wait_until_ignoring
```

**Comment by manycoding** [comment]
Hi, so I tried your patch but still observe StaleElementReferenceException.
My test looks something like this:

```
Library             ../WaitingKeywordsMonkeyPatches.py

Wait For Step
    @{old_ignored}=    Set Ignored Wait Exceptions    StaleElementReferenceException
    Wait Until Element Contains    //span[. = "${step}"]/../../../..//td[@colid = "state"]/div    ${state}    timeout=60
    Set Ignored Wait Exceptions    @{old_ignored}
```

And the log:

```
KEYWORD @{old_ignored} = Selenium2Library . Set Ignored Wait Exceptions StaleElementReferenceException
Documentation:  Sets the exceptions to ignore while waiting.
Start / End / Elapsed:  20151119 13:47:11.066 / 20151119 13:47:11.067 / 00:00:00.001
13:47:11.067    TRACE   Arguments: [ 'StaleElementReferenceException' ]     
13:47:11.067    TRACE   Return: [b'StaleElementReferenceException']     
13:47:11.067    INFO    @{old_ignored} = [ StaleElementReferenceException ]     

00:00:03.918 KEYWORD Selenium2Library . Wait Until Element Contains //span[. = "${step}"]/../../../..//td[@colid = "state"]/div, ${state}, timeout=60
Documentation:  Waits until given element contains `text`.
Start / End / Elapsed:  20151119 13:47:11.067 / 20151119 13:47:14.985 / 00:00:03.918
00:00:00.092 KEYWORD Selenium2Library . Capture Page Screenshot
13:47:11.068    TRACE   Arguments: [ '//span[. = "Get System values."]/../../../..//td[@colid = "state"]/div' | 'Complete' | timeout='60' ]     
13:47:11.068    DEBUG   POST http://127.0.0.1:55665/hub/session/a2acc057-42eb-4f69-8f1a-0afa3fa54294/elements {"using": "xpath", "sessionId": "a2acc057-42eb-4f69-8f1a-0afa3fa54294", "value": "//span[. = \"Get System values.\"]/../../../..//td[@colid = \"state\"]/div"}    
13:47:11.161    DEBUG   Finished Request    
13:47:11.162    DEBUG   GET http://127.0.0.1:55665/hub/session/a2acc057-42eb-4f69-8f1a-0afa3fa54294/element/{1c515c48-babe-48eb-8526-829767b0ff4c}/text {"sessionId": "a2acc057-42eb-4f69-8f1a-0afa3fa54294", "id": "{1c515c48-babe-48eb-8526-829767b0ff4c}"}   
13:47:11.184    DEBUG   Finished Request    
13:47:11.384    DEBUG   GET http://127.0.0.1:55665/hub/session/a2acc057-42eb-4f69-8f1a-0afa3fa54294/element/{1c515c48-babe-48eb-8526-829767b0ff4c}/text {"sessionId": "a2acc057-42eb-4f69-8f1a-0afa3fa54294", "id": "{1c515c48-babe-48eb-8526-829767b0ff4c}"}   
13:47:14.892    DEBUG   Finished Request    
13:47:14.985    FAIL    StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up
Stacktrace:
    at fxdriver.cache.getElementAt (resource://fxdriver/modules/web-element-cache.js:9335)
    at Utils.getElementAt (file:///tmp/tmpF19CEz/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/command-processor.js:8928)
    at WebElement.getElementText (file:///tmp/tmpF19CEz/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/command-processor.js:12057)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpF19CEz/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/command-processor.js:12617)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmpF19CEz/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/command-processor.js:623)     
13:47:14.985    DEBUG   Traceback (most recent call last):
  File "<decorator-gen-162>", line 2, in wait_until_element_contains
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 200, in wait_until_element_contains
    self._wait_until_no_error(timeout, check_text)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 237, in _wait_until_no_error
    timeout_error = wait_func(*args)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 194, in check_text
    actual = element.text
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 70, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 453, in _execute
    return self._parent.execute(command, params)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/webdrivermonkeypatches.py", line 11, in execute
    result = self._base_execute(driver_command, params)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)  
13:47:11.065    TRACE   Arguments: [ ${step}='Get System values.' | ${state}='Complete' ]
```

**Comment by ombre42** [comment]
The patch was effective in earlier versions of the library (<1.3). The code has changed (897646f) and the keyword you are calling does not use the patched private method `_wait_until`. It uses `_wait_until_no_error`. The patch would need to modified to be effective in newer versions and I have not updated it.

**Comment by manycoding** [comment]
I updated the patch, it should work now.
The only problem is while waiting the actual element changes.
For example, if I use Wait Until Element Contains I'll only get the stale value, not the one I'm looking for.
By the way, how do you import the file properly to avoid the "contains no keywords" warning?

```
import re
import time
import robot
from robot.api import logger
import selenium.common.exceptions as exceptions
from Selenium2Library import utils
from Selenium2Library.keywords.keywordgroup import KeywordGroup
from Selenium2Library.keywords import _WaitingKeywords


class SeleniumExceptionMatcher(object):

    def __init__(self, user_repr):
        exclass, _, regexp = user_repr.partition('|')
        if not hasattr(exceptions, exclass):
            raise ValueError("selenium.common.exceptions does not define %s" % exclass)
        self._exception = getattr(exceptions, exclass)
        if regexp:
            try:
                self._regexp = re.compile(regexp)
            except Exception, e:
                raise ValueError("Bad regular expression '%s': %s" % (regexp, e))
        else:
            self._regexp = None

    def matches(self, ex):
        if not isinstance(ex, self._exception):
            return False
        if self._regexp:
            if not self._regexp.search(ex.msg):
                logger.debug("Pattern '%s' not found in exception message '%s'" \
                             % (self._regexp.pattern, ex.msg))
                return False
        return True

    def user_repr(self):
        repr = self._exception.__name__
        if self._regexp:
            repr += '|' + self._regexp.pattern
        return repr


class _WaitingKeywordsMonkeyPatches(KeywordGroup):

    def __init__(self): # no init before patching
        # key:browser instance, value:SeleniumExceptionMatcher[]
        self._exception_matchers = {}

    def set_ignored_wait_exceptions(self, *exceptions):
        """Sets the exceptions to ignore while waiting.

        `exceptions` must be exception class names defined in 
        selenium.common.exceptions. The exceptions will be ignored by the Wait 
        Until * keywords in Selenium2Library for the _current_ browser 
        instance. For more control a regular expression can be appended to 
        the exception class after a pipe. When a regular expression is 
        specified, an instance will only be ignored if the exception message 
        matches the regular expression. The same exception can appear multiple 
        times. 

        Example:
        | @{old ignored}=                  | Set Ignored Wait Exceptions | InvalidSelectorException | WebDriverException|modal |
        | Wait Until Page Contains Element | id=name                     |                           |                          |
        | Set Ignored Wait Exceptions      | @{old ignored}              | # restore previous        |                          |
        """
        browser = self._current_browser()
        old_ex_matchers = self._exception_matchers.get(browser) or []
        ex_matchers = [SeleniumExceptionMatcher(ex) for ex in exceptions]
        self._exception_matchers[browser] = ex_matchers
        return [em.user_repr() for em in old_ex_matchers]

    def _wait_until_no_error_ignoring(self, timeout, wait_func, *args):
        timeout = robot.utils.timestr_to_secs(timeout) if timeout is not None else self._timeout_in_secs
        maxtime = time.time() + timeout
        matchers = self._exception_matchers.get(self._current_browser()) or []
        ignored_names = []
        while True:
            try:
                timeout_error = wait_func(*args)
                if not timeout_error: return
            except exceptions.WebDriverException, e:
                ignored = False
                for ex_matcher in matchers:
                    if ex_matcher.matches(e):
                        ignored = True
                        name = e.__class__.__name__
                        # log warn level event at most once per exception type per wait
                        if name not in ignored_names:
                            ignored_names.append(name)
                            self._info("Ignored during wait: %s: %s" % (name, e))
                        else:
                            self._debug("Ignored during wait: %s: %s" % (name, e))
                        break
                if not ignored:
                    raise
            if time.time() > maxtime:
                raise AssertionError(timeout_error)
            time.sleep(0.2)

    _WaitingKeywords.__init__ = __init__
    _WaitingKeywords.set_ignored_wait_exceptions = set_ignored_wait_exceptions
    _WaitingKeywords._wait_until_no_error = _wait_until_no_error_ignoring
```

**Comment by ombre42** [comment]
That's great that you updated it. The patch mentioned above is just part of a much larger file that also contains a class with keywords to extend Selenium2Library. That is why we do not get the no keywords warning. The important part is that the monkey patch class is loaded _before_ any instance of Selenium2Library is created.

As for your issue with `wait_until_element_contains`, that appears to be an issue specific to that keyword and `wait_until_element_does_not_contain`. These keywords perform the element search first and then wait for the text to change. Notice that the call to `_element_find` is outside the function passed to `_wait_until_no_error`. All the other wait keywords locate the element upon every poll (inside the function passed to `_wait_until_no_error`).

This is where it gets into a grey area. Some people would like to know when the AUT is replacing the elements in the DOM, and others would rather it "just work". Personally, I think it would be better to change these two keywords to (re) locate the element on every poll.

**Comment by aaltat** [comment]
The issue #475 has a discussion how the Wait\* keywords should be enhanced to avoid this type of problems.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by ombre42** [comment]
I cannot comment on whether this is valid anymore. Since we customized Selenium2Library to ignore this error, I do not know if it still occurs. Closing since no one else has acknowledged getting this error as far as I can remember.

**Comment by EslaMahgoub** [comment]
ombre42
could you give me the customized Selenium2Library because I still have this issue ?
