### ISSUE TITLE
>pip install webdrivermanager - Getting requirements to build wheel did not run successfully.

### ISSUE THREAD

**Issue by sathishalthus-learning** [robotframework/SeleniumLibrary#1878]
# Prerequisites

# For issues
## Steps to reproduce the issue
pip install robotframework
pip install --upgrade robotframework-seleniumlibrary
pip install webdrivermanager
-- note : both in c: or in virtual environment

## Error messages and additional information

Collecting webdrivermanager
  Using cached webdrivermanager-0.10.0.tar.gz (33 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
 exit code: 1
  ╰─> [31 lines of output]
      C:\Users\Sathish Althus\AppData\Local\Temp\pip-install-iepgg5o1\webdrivermanager_8109961131654d29879155c324efd338\versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "d:\workspaces\python\tutorial-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "d:\workspaces\python\tutorial-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "d:\workspaces\python\tutorial-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Sathish Althus\AppData\Local\Temp\pip-build-env-7aw67l2_\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Sathish Althus\AppData\Local\Temp\pip-build-env-7aw67l2_\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Sathish Althus\AppData\Local\Temp\pip-build-env-7aw67l2_\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Sathish Althus\AppData\Local\Temp\pip-build-env-7aw67l2_\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 47, in <module>
        File "C:\Users\Sathish Althus\AppData\Local\Temp\pip-install-iepgg5o1\webdrivermanager_8109961131654d29879155c324efd338\versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\Sathish Althus\AppData\Local\Temp\pip-install-iepgg5o1\webdrivermanager_8109961131654d29879155c324efd338\versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Sathish Althus\AppData\Local\Temp\pip-install-iepgg5o1\webdrivermanager_8109961131654d29879155c324efd338\versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

## Expected behavior and actual behavior

webdriver installed successfully

## Environment

Operating System: Windows 11
Libraries
- Robot Framework: robotframework-7.0
- Selenium: Version
- SeleniumLibrary:   robotframework-seleniumlibrary-6.2.0

**Comment by MarkNewell-OMES** [comment]
Were you ever able to fix this error? I'm getting the same error and have so far found no fix.

**Comment by rasjani** [comment]
1.  Since Selenium (the python side) now has selenium-manager baked into its python distribution - webdrivermanager is somewhat obsolete. It provides the same functionality as webdrivermanager but *at runtime* if underlying Selenium is new enough.
2. Maybe this issue should be moved to https://github.com/MarketSquare/webdrivermanager/issues
3.  Submitted  a patch to fix the issue; https://github.com/MarketSquare/webdrivermanager/pull/106

**Comment by emanlove** [comment]
Closing this as this is a webdrivermanager issue and @rasjani has a fix there. In addtion I do strongly recommend people shift to using the built in selenium manager.
