### ISSUE TITLE
Close Browser fail when Set Selenium Speed >=2s in firefox

### ISSUE THREAD

**Issue by xuyp** [robotframework/SeleniumLibrary#196]
Selenium2Library1.1.0
selenium2.31.0
firefox 17.0.5

**\* Settings ***
Library           Selenium2Library

**\* Test Cases ***
closeBrowser
        Set Selenium Speed    2
        Set Log Level    DEBUG
        Open Browser    http://weibo.com/    ff
        Close Browser

KEYWORD:  Selenium2Library.Close Browser  

Documentation:

Closes the current browser.

Start / End / Elapsed:
20130427 17:02:12.839 / 20130427 17:02:15.895 / 00:00:03.056 

Expand All KEYWORD:  Selenium2Library.Capture Page Screenshot  

Documentation:

Takes a screenshot of the current page and embeds it into the log.

Start / End / Elapsed:
20130427 17:02:14.872 / 20130427 17:02:15.888 / 00:00:01.016 

17:02:14.875 DEBUG GET http://127.0.0.1:52191/hub/session/05bfeba4-5d94-45e8-b412-2319acc69ebe/screenshot {"sessionId": "05bfeba4-5d94-45e8-b412-2319acc69ebe"} 

17:02:15.886 FAIL URLError: <urlopen error [Errno 10061] > 

17:02:15.886 DEBUG Traceback (most recent call last):
  File "<string>", line 2, in capture_page_screenshot
  File "D:\Python27\lib\site-packages\robotframework_selenium2library-1.1.0-py2.7.egg\Selenium2Library\keywords\keywordgroup.py", line 12, in _run_on_failure_decorator
    return method(_args, *_kwargs)
  File "D:\Python27\lib\site-packages\robotframework_selenium2library-1.1.0-py2.7.egg\Selenium2Library\keywords_screenshot.py", line 29, in capture_page_screenshot
    self._current_browser().get_screenshot_as_file(path)
  File "D:\Python27\lib\site-packages\selenium-2.31.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 707, in get_screenshot_as_file
    png = self.execute(Command.SCREENSHOT)['value']
  File "D:\Python27\lib\site-packages\robotframework_selenium2library-1.1.0-py2.7.egg\Selenium2Library\webdrivermonkeypatches.py", line 11, in execute
    result = self._base_execute(driver_command, params)
  File "D:\Python27\lib\site-packages\selenium-2.31.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 158, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\selenium-2.31.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 340, in execute
    return self._request(url, method=command_info[0], data=data)
  File "D:\Python27\lib\site-packages\selenium-2.31.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 387, in _request
    response = opener.open(request)
  File "D:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1177, in do_open
    raise URLError(err) 

17:02:12.840 DEBUG Closing browser with session id 05bfeba4-5d94-45e8-b412-2319acc69ebe 

17:02:12.841 DEBUG DELETE http://127.0.0.1:52191/hub/session/05bfeba4-5d94-45e8-b412-2319acc69ebe {"sessionId": "05bfeba4-5d94-45e8-b412-2319acc69ebe"} 

17:02:15.888 WARN Keyword 'Capture Page Screenshot' could not be run on failure: URLError: <urlopen error [Errno 10061] > 

17:02:15.894 FAIL WindowsError: [Error 5]  

17:02:15.894 DEBUG Traceback (most recent call last):
  File "<string>", line 2, in close_browser
  File "D:\Python27\lib\site-packages\robotframework_selenium2library-1.1.0-py2.7.egg\Selenium2Library\keywords\keywordgroup.py", line 12, in _run_on_failure_decorator
    return method(_args, *_kwargs)
  File "D:\Python27\lib\site-packages\robotframework_selenium2library-1.1.0-py2.7.egg\Selenium2Library\keywords_browsermanagement.py", line 52, in close_browser
    self._cache.close()
  File "D:\Python27\lib\site-packages\robotframework_selenium2library-1.1.0-py2.7.egg\Selenium2Library\utils\browsercache.py", line 23, in close
    browser.quit()
  File "D:\Python27\lib\site-packages\selenium-2.31.0-py2.7.egg\selenium\webdriver\firefox\webdriver.py", line 74, in quit
    self.binary.kill()
  File "D:\Python27\lib\site-packages\selenium-2.31.0-py2.7.egg\selenium\webdriver\firefox\firefox_binary.py", line 56, in kill
    self.process.kill()
  File "D:\Python27\lib\subprocess.py", line 1019, in terminate
    _subprocess.TerminateProcess(self._handle, 1)

**Comment by ombre42** [comment]
I do not see how Set Selenium Speed plays into this issue. The problem seems to be in how Selenium handles a child process. There is an [open issue](https://code.google.com/p/selenium/issues/detail?id=5604) in Selenium's tracker regarding this.

I'm not sure what Selenium2Library could do to mitigate this issue. Could you please provide more information as to what the problem is and when it occurs?

**Comment by aaltat** [comment]
Because we are closing old issues if they are not anymore valid. If you feel that this issue is valid and should be fixed on Selenium2Library side, please send an update. If update is not received, we will close the issue.

**Comment by aaltat** [comment]
Closing issue because of the inactivity
