### ISSUE TITLE
Selenium Timeout doesn't affect Open Browser or Go To

### ISSUE THREAD

**Issue by manycoding** [robotframework/SeleniumLibrary#532]
As far as I understand, timeout is set before browser.get(url) in open_browser [_browsermanagement.py](https://github.com/robotframework/Selenium2Library/blob/master/src/Selenium2Library/keywords/_browsermanagement.py)
Also I checked Go To just to be sure that issue isn't related to the opening of a browser itself.
Specifying timeout in import doesn't solve the problem also.

Problem is I have a page which loads a few minutes.

Could be a related issue https://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=84

**Comment by aaltat** [comment]
The code is different but  by a quick read, it is true that default selenium timeout is not changed, when the driver is created. But I think your point is valid and we should allow a timeout to be defined.

But which timeout to use, if we change the code to use the default timeout, 5s by default, it is a big back ward incompatible issue and it will break many tests (including mine). Also I don't know is having separate timeout for this a good idea. By quick glance, it seems to be the way selenium does it, but we need to discuss is it a way we want to do it. Any good ideas from anyone?

**Comment by aaltat** [comment]
As a workaround, have you tried the Create Webdriver keyword?

**Comment by manycoding** [comment]
I'm not sure how to open a url using Create Webdriver.
It seems I need to create a webdriver first and then use selenium.open.

I see neither Open Browser nor selenium.open don't have any timeout arguments.
What I want is to fail the test if a page is loading more than X seconds.

Here's what I've tried:
    Create Webdriver    Firefox    timeout=5
    Set Selenium Timeout    5
    Go To    ${SERVER}

**Comment by aaltat** [comment]
The timeout is defined when the driver object is created. How to define the timeout depends on the browser, so which browser you are using?

**Comment by aaltat** [comment]
I did some testing and setting the timeout is problematic with Chrome. It is problematic because [Chrome Webdriver](http://selenium-python.readthedocs.org/api.html#module-selenium.webdriver.chrome.webdriver) is based on the [Remote Webdriver](http://selenium-python.readthedocs.org/api.html#module-selenium.webdriver.remote.webdriver) and you should be able to call driver object [set_page_load_timeout](http://selenium-python.readthedocs.org/api.html#selenium.webdriver.remote.webdriver.WebDriver.set_page_load_timeout). In Python, you should do this:

```
from selenium import webdriver

driver = webdriver.Chrome()
driver.set_page_load_timeout(180)
```

But because S2L does not expose the driver object for you, you can not do it. Although it should be easy to create extension keyword to S2L, which does the above for you. 

But in [Firefox Webdriver](http://selenium-python.readthedocs.org/api.html#module-selenium.webdriver.firefox.webdriver), the timeout can be given as (keyword) argument. I did not have page that would take that long to load, but I do not see why this should not work you:

```
    Selenium2Library.Create Webdriver
    ...    Firefox
    ...    timeout\=1
    Selenium2Library.Go To    http://selenium-python.readthedocs.org/api.html#module-selenium.webdriver.firefox.webdriver
    Selenium2Library.Wait Until Page Contains    Selenium
    [Teardown]    Selenium2Library.Close All Browsers
```

If it does not work you, could you run only the relevant keywords and send the log, with `--loglevel trace` enabled?

**Comment by manycoding** [comment]
Here you go:

```
**OPEN BROWSER**
TEST Test Timeout
Full Name:  Debug.Test Timeout
Start / End / Elapsed:  20151117 11:40:16.525 / 20151117 11:43:22.646 / **00:03:06.121**
Status:     PASS (critical)
00:00:00.055 KEYWORD BuiltIn . Import Library Selenium2Library
Documentation:  

Imports a library with the given name and optional arguments.
Start / End / Elapsed:  20151117 11:40:16.525 / 20151117 11:40:16.580 / **00:00:00.055**
11:40:16.526    TRACE   Arguments: [ 'Selenium2Library' ]   
11:40:16.580    TRACE   Return: None    
00:00:00.001 KEYWORD Selenium2Library . Set Selenium Timeout 1
Documentation:  

Sets the timeout in seconds used by various keywords.
Start / End / Elapsed:  20151117 11:40:16.580 / 20151117 11:40:16.581 / **00:00:00.001**
11:40:16.581    TRACE   Arguments: [ '1' ]  
11:40:16.581    TRACE   Return: b'5 seconds'    
00:03:05.995 KEYWORD Selenium2Library . Open Browser ${URL}, firefox
Documentation:  

Opens a new browser instance to given URL.
Start / End / Elapsed:  20151117 11:40:16.581 / 20151117 11:43:22.576 / **00:03:05.995**
11:40:16.582    TRACE   Arguments: [ 'https://pev.com/' | 'firefox' ]   
11:40:16.582    INFO    Opening browser 'firefox' to base url 'https://pev.com/'    
11:40:18.647    DEBUG   POST http://127.0.0.1:35760/hub/session {"desiredCapabilities": {"platform": "ANY", "browserName": "firefox", "version": "", "marionette": false, "javascriptEnabled": true}}   
11:40:18.698    DEBUG   Finished Request    
11:40:18.698    DEBUG   POST http://127.0.0.1:35760/hub/session/a8605ce3-e20c-4c63-9a2d-e3b80ec7119e/timeouts/async_script {"sessionId": "a8605ce3-e20c-4c63-9a2d-e3b80ec7119e", "ms": 1000.0}  
11:40:22.500    DEBUG   Finished Request    
11:40:22.501    DEBUG   POST http://127.0.0.1:35760/hub/session/a8605ce3-e20c-4c63-9a2d-e3b80ec7119e/timeouts/implicit_wait {"sessionId": "a8605ce3-e20c-4c63-9a2d-e3b80ec7119e", "ms": 0.0}    
11:40:22.506    DEBUG   Finished Request    
11:40:22.507    DEBUG   POST http://127.0.0.1:35760/hub/session/a8605ce3-e20c-4c63-9a2d-e3b80ec7119e/url {"url": "https://pev.com/", "sessionId": "a8605ce3-e20c-4c63-9a2d-e3b80ec7119e"}   
11:43:22.575    DEBUG   Finished Request    
11:43:22.575    DEBUG   Opened browser with session id a8605ce3-e20c-4c63-9a2d-e3b80ec7119e     
11:43:22.576    TRACE   Return: 1   
00:00:00.048 KEYWORD Selenium2Library . Wait Until Page Contains com
Documentation:  

Waits until `text` appears on current page.
Start / End / Elapsed:  20151117 11:43:22.576 / 20151117 11:43:22.624 / **00:00:00.048**
11:43:22.577    TRACE   Arguments: [ 'com' ]    
11:43:22.577    DEBUG   POST http://127.0.0.1:35760/hub/session/a8605ce3-e20c-4c63-9a2d-e3b80ec7119e/elements {"using": "xpath", "sessionId": "a8605ce3-e20c-4c63-9a2d-e3b80ec7119e", "value": "//*[contains(., 'com')]"}   
11:43:22.624    DEBUG   Finished Request    
11:43:22.624    TRACE   Return: None

**CREATE WEBDRIVER**
TEST Test Timeout
Full Name:  Debug.Test Timeout
Start / End / Elapsed:  20151117 11:32:36.699 / 20151117 11:35:39.107 / **00:03:02.408**
Status:     FAIL (critical)
Message:    Text 'com' did not appear in 5 seconds

00:00:00.055 KEYWORD BuiltIn . Import Library Selenium2Library
Documentation:  
Imports a library with the given name and optional arguments.
Start / End / Elapsed:  20151117 11:32:36.700 / 20151117 11:32:36.755 / **00:00:00.055**
11:32:36.700    TRACE   Arguments: [ 'Selenium2Library' ]   
11:32:36.755    TRACE   Return: None    

00:00:02.169 KEYWORD Selenium2Library . Create Webdriver Firefox, timeout=0.1
Documentation:  
Creates an instance of a WebDriver.
Start / End / Elapsed:  20151117 11:32:36.756 / 20151117 11:32:38.925 / **00:00:02.169**
11:32:36.756    TRACE   Arguments: [ 'Firefox' | timeout='0.1' ]    
11:32:36.756    INFO    Creating an instance of the Firefox WebDriver   
11:32:38.820    DEBUG   POST http://127.0.0.1:38331/hub/session {"desiredCapabilities": {"platform": "ANY", "browserName": "firefox", "version": "", "marionette": false, "javascriptEnabled": true}}   
11:32:38.924    DEBUG   Finished Request    
11:32:38.924    DEBUG   Created Firefox WebDriver instance with session id 6ce7cf1f-60e1-42a0-894c-9152b23bad0e     
11:32:38.924    TRACE   Return: 1   

00:00:00.028 KEYWORD Selenium2Library . Go To ${URL}
Documentation:  
Navigates the active browser instance to the provided URL.
Start / End / Elapsed:  20151117 11:32:38.925 / 20151117 11:32:38.953 / **00:00:00.028**
11:32:38.926    TRACE   Arguments: [ 'https://pev.com/' ]   
11:32:38.926    INFO    Opening url 'https://pev.com/'  
11:32:38.926    DEBUG   POST http://127.0.0.1:38331/hub/session/6ce7cf1f-60e1-42a0-894c-9152b23bad0e/url {"url": "https://pev.com/", "sessionId": "6ce7cf1f-60e1-42a0-894c-9152b23bad0e"}   
11:32:38.952    DEBUG   Finished Request    
11:32:38.953    TRACE   Return: None    

00:03:00.135 KEYWORD Selenium2Library . Wait Until Page Contains com
Documentation:  
Waits until `text` appears on current page.
Start / End / Elapsed:  20151117 11:32:38.953 / 20151117 11:35:39.088 / **00:03:00.135**
11:32:38.953    TRACE   Arguments: [ 'com' ]    
11:32:38.954    DEBUG   POST http://127.0.0.1:38331/hub/session/6ce7cf1f-60e1-42a0-894c-9152b23bad0e/elements {"using": "xpath", "sessionId": "6ce7cf1f-60e1-42a0-894c-9152b23bad0e", "value": "//*[contains(., 'com')]"}   
11:35:39.032    DEBUG   Finished Request    
11:35:39.088    FAIL    Text 'com' did not appear in 5 seconds  
11:35:39.088    DEBUG   Traceback (most recent call last):
  File "<decorator-gen-156>", line 2, in wait_until_page_contains
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 46, in wait_until_page_contains
    self._wait_until(timeout, error, self._is_text_present, text)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 231, in _wait_until
    self._wait_until_no_error(timeout, wait_func)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 240, in _wait_until_no_error
    raise AssertionError(timeout_error)
```

**Comment by aaltat** [comment]
But now you are demonstrating a problem with the `Wait Until Page Contains` keyword. I did understand that you have a problem with the `Open Browser` or `Go To` keywords.

Could you show the problem where the page load takes minutes. I am interested on keyword what you use and stack trace seen in the log.

**Comment by manycoding** [comment]
Let me explain. The problem is that simply there's no timeout to limit page loading time.
In the first log as you can see I used the Open Browser keyword to open the page. It took three minutes until the test was finished and the page itself still didn't load.

```
OPEN BROWSER
TEST Test Timeout
Full Name:  Debug.Test Timeout
Start / End / Elapsed:  20151117 11:40:16.525 / 20151117 11:43:22.646 / 00:03:06.121
Status:     PASS (critical)

00:00:00.055 KEYWORD BuiltIn . Import Library Selenium2Library
Documentation:  Imports a library with the given name and optional arguments.
Start / End / Elapsed:  20151117 11:40:16.525 / 20151117 11:40:16.580 / **00:00:00.055**
11:40:16.526    TRACE   Arguments: [ 'Selenium2Library' ]   
11:40:16.580    TRACE   Return: None    

00:00:00.001 KEYWORD Selenium2Library . Set Selenium Timeout 1
Documentation:  Sets the timeout in seconds used by various keywords.
Start / End / Elapsed:  20151117 11:40:16.580 / 20151117 11:40:16.581 / 00:00:00.001
11:40:16.581    TRACE   Arguments: [ '1' ]  
11:40:16.581    TRACE   Return: b'5 seconds'    

00:03:05.995 KEYWORD Selenium2Library . Open Browser ${URL}, firefox
Documentation:  Opens a new browser instance to given URL.
Start / End / Elapsed:  20151117 11:40:16.581 / 20151117 11:43:22.576 / 00:03:05.995
11:40:16.582    TRACE   Arguments: [ 'https://pev.com/' | 'firefox' ]    
11:40:16.582    INFO    Opening browser 'firefox' to base url 'https://pev.com/'     
11:40:18.647    DEBUG   POST http://127.0.0.1:35760/hub/session {"desiredCapabilities": {"platform": "ANY", "browserName": "firefox", "version": "", "marionette": false, "javascriptEnabled": true}}   
11:40:18.698    DEBUG   Finished Request    
11:40:18.698    DEBUG   POST http://127.0.0.1:35760/hub/session/a8605ce3-e20c-4c63-9a2d-e3b80ec7119e/timeouts/async_script {"sessionId": "a8605ce3-e20c-4c63-9a2d-e3b80ec7119e", "ms": 1000.0}  
11:40:22.500    DEBUG   Finished Request    
11:40:22.501    DEBUG   POST http://127.0.0.1:35760/hub/session/a8605ce3-e20c-4c63-9a2d-e3b80ec7119e/timeouts/implicit_wait {"sessionId": "a8605ce3-e20c-4c63-9a2d-e3b80ec7119e", "ms": 0.0}    
11:40:22.506    DEBUG   Finished Request    
11:40:22.507    DEBUG   POST http://127.0.0.1:35760/hub/session/a8605ce3-e20c-4c63-9a2d-e3b80ec7119e/url {"url": "https://pev.com/", "sessionId": "a8605ce3-e20c-4c63-9a2d-e3b80ec7119e"}    
11:43:22.575    DEBUG   Finished Request    
11:43:22.575    DEBUG   Opened browser with session id a8605ce3-e20c-4c63-9a2d-e3b80ec7119e     
11:43:22.576    TRACE   Return: 1
```

In the second example I used Create Webdriver and Go To keywords. Also, I inserted Wait Until Page Contains simply because Go To doesn't check if the actual page is loaded (in that case default Mozilla tab was present instead). It took same time to finish the test, but the page I needed didn't load.

```
CREATE WEBDRIVER
TEST Test Timeout
Full Name:  Debug.Test Timeout
Start / End / Elapsed:  20151117 11:32:36.699 / 20151117 11:35:39.107 / 00:03:02.408
Status:     FAIL (critical)
Message:    Text 'com' did not appear in 5 seconds

00:00:00.055 KEYWORD BuiltIn . Import Library Selenium2Library
Documentation:  Imports a library with the given name and optional arguments.
Start / End / Elapsed:  20151117 11:32:36.700 / 20151117 11:32:36.755 / 00:00:00.055
11:32:36.700    TRACE   Arguments: [ 'Selenium2Library' ]   
11:32:36.755    TRACE   Return: None    

00:00:02.169 KEYWORD Selenium2Library . Create Webdriver Firefox, timeout=0.1
Documentation:  
Creates an instance of a WebDriver.
Start / End / Elapsed:  20151117 11:32:36.756 / 20151117 11:32:38.925 / 00:00:02.169
11:32:36.756    TRACE   Arguments: [ 'Firefox' | timeout='0.1' ]    
11:32:36.756    INFO    Creating an instance of the Firefox WebDriver   
11:32:38.820    DEBUG   POST http://127.0.0.1:38331/hub/session {"desiredCapabilities": {"platform": "ANY", "browserName": "firefox", "version": "", "marionette": false, "javascriptEnabled": true}}   
11:32:38.924    DEBUG   Finished Request    
11:32:38.924    DEBUG   Created Firefox WebDriver instance with session id 6ce7cf1f-60e1-42a0-894c-9152b23bad0e     
11:32:38.924    TRACE   Return: 1   

00:00:00.028 KEYWORD Selenium2Library . Go To ${URL}
Documentation:  
Navigates the active browser instance to the provided URL.
Start / End / Elapsed:  20151117 11:32:38.925 / 20151117 11:32:38.953 / 00:00:00.028
11:32:38.926    TRACE   Arguments: [ 'https://pev.com/' ]    
11:32:38.926    INFO    Opening url 'https://pev.com/'   
11:32:38.926    DEBUG   POST http://127.0.0.1:38331/hub/session/6ce7cf1f-60e1-42a0-894c-9152b23bad0e/url {"url": "https://pev.com/", "sessionId": "6ce7cf1f-60e1-42a0-894c-9152b23bad0e"}    
11:32:38.952    DEBUG   Finished Request    
11:32:38.953    TRACE   Return: None    

00:03:00.135 KEYWORD Selenium2Library . Wait Until Page Contains com
Documentation:  
Waits until `text` appears on current page.
Start / End / Elapsed:  20151117 11:32:38.953 / 20151117 11:35:39.088 / 00:03:00.135
11:32:38.953    TRACE   Arguments: [ 'com' ]    
11:32:38.954    DEBUG   POST http://127.0.0.1:38331/hub/session/6ce7cf1f-60e1-42a0-894c-9152b23bad0e/elements {"using": "xpath", "sessionId": "6ce7cf1f-60e1-42a0-894c-9152b23bad0e", "value": "//*[contains(., 'com')]"}   
11:35:39.032    DEBUG   Finished Request    
11:35:39.088    FAIL    Text 'com' did not appear in 5 seconds  
11:35:39.088    DEBUG   Traceback (most recent call last):
  File "<decorator-gen-156>", line 2, in wait_until_page_contains
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 46, in wait_until_page_contains
    self._wait_until(timeout, error, self._is_text_present, text)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 231, in _wait_until
    self._wait_until_no_error(timeout, wait_func)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 240, in _wait_until_no_error
    raise AssertionError(timeout_error)
```

All in all, nor timeout limits page loading time, neither Go To and Open Browser fail if the page doesn't load.

**Comment by aaltat** [comment]
So the problem is not in `Open Browser` or `Go To` keywords or at least you do not get a timeout error. Explaining why this works in this way, requires explaining how Selenium2Library and selenium works. The both keywords perform [selenium get](http://selenium-python.readthedocs.org/navigating.html) behind the scenes and the `selenium get` listens the `onload` event from the browser. That, in theory, should confirm that page is loaded. But in real world, that doesn't never work and all my URL navigation's look like this:

```
| Open Browser | www.url.com |
| Wait Until Page Contains Element | xpath=/something/here | timeout=some number here |
```

Note that this is not a problem in the Selenium2Library or in the selenium implementation, this is the way modern browsers and web applications do work.

**Comment by manycoding** [comment]
Thank you for the clarification.
Maybe you consider adding a note regarding this in the user guide?

Back to the issue - I still don't know how to fail a test if page loads more than 15 seconds.
I specified all existing timeouts.

```
KEYWORD BuiltIn . Import Library Selenium2Library, timeout=1
Documentation:     Imports a library with the given name and optional arguments.
Start / End / Elapsed:     20151119 11:04:24.659 / 20151119 11:04:24.694 / 00:00:00.035
11:04:24.659     TRACE     Arguments: [ 'Selenium2Library' | 'timeout=1' ]     
11:04:24.694     TRACE     Return: None     

00:00:02.137 KEYWORD Selenium2Library . Create Webdriver ${BROWSER}, timeout=1
Documentation:     Creates an instance of a WebDriver.
Start / End / Elapsed:     20151119 11:04:24.694 / 20151119 11:04:26.831 / 00:00:02.137
11:04:24.695     TRACE     Arguments: [ 'Firefox' | timeout='1' ]     
11:04:24.695     INFO     Creating an instance of the Firefox WebDriver     
11:04:26.758     DEBUG     POST http://127.0.0.1:48802/hub/session {"desiredCapabilities": {"platform": "ANY", "browserName": "firefox", "version": "", "marionette": false, "javascriptEnabled": true}}     
11:04:26.829     DEBUG     Finished Request     
11:04:26.830     DEBUG     Created Firefox WebDriver instance with session id 26f23ade-0f00-47bb-aaac-dd9ffc073dcd     
11:04:26.831     TRACE     Return: 1     

00:00:02.454 KEYWORD Selenium2Library . Set Selenium Timeout 1
Documentation:     Sets the timeout in seconds used by various keywords.
Start / End / Elapsed:     20151119 11:04:26.832 / 20151119 11:04:29.286 / 00:00:02.454
11:04:26.833     TRACE     Arguments: [ '1' ]     
11:04:26.833     DEBUG     POST http://127.0.0.1:48802/hub/session/26f23ade-0f00-47bb-aaac-dd9ffc073dcd/timeouts/async_script {"sessionId": "26f23ade-0f00-47bb-aaac-dd9ffc073dcd", "ms": 1000.0}     
11:04:29.285     DEBUG     Finished Request     
11:04:29.285     TRACE     Return: b'5 seconds'     

00:03:00.070 KEYWORD Selenium2Library . Go To ${URL}
Documentation:     Navigates the active browser instance to the provided URL.
Start / End / Elapsed:     20151119 11:04:29.286 / 20151119 11:07:29.356 / 00:03:00.070
11:04:29.286     TRACE     Arguments: [ 'https://pev.com' ]     
11:04:29.287     INFO     Opening url 'https://pev.com'     
11:04:29.287     DEBUG     POST http://127.0.0.1:48802/hub/session/26f23ade-0f00-47bb-aaac-dd9ffc073dcd/url {"url": "https://pev.com", "sessionId": "26f23ade-0f00-47bb-aaac-dd9ffc073dcd"}     
11:07:29.356     DEBUG     Finished Request     
11:07:29.356     TRACE     Return: None     

00:00:01.246 KEYWORD Selenium2Library . Wait Until Page Contains Element //title[text() = "${SERVER}"], timeout=1
Documentation:     Waits until element specified with `locator` appears on current page.
Start / End / Elapsed:     20151119 11:07:29.356 / 20151119 11:07:30.602 / 00:00:01.246
11:07:29.357     TRACE     Arguments: [ '//title[text() = "pev.com"]' | timeout='1' ]     
11:07:29.357     DEBUG     POST http://127.0.0.1:48802/hub/session/26f23ade-0f00-47bb-aaac-dd9ffc073dcd/elements {"using": "xpath", "sessionId": "26f23ade-0f00-47bb-aaac-dd9ffc073dcd", "value": "//title[text() = \"pev.com\"]"}     
11:07:29.364     DEBUG     Finished Request     
11:07:29.565     DEBUG     POST http://127.0.0.1:48802/hub/session/26f23ade-0f00-47bb-aaac-dd9ffc073dcd/elements {"using": "xpath", "sessionId": "26f23ade-0f00-47bb-aaac-dd9ffc073dcd", "value": "//title[text() = \"pev.com\"]"}     
11:07:29.572     DEBUG     Finished Request     
11:07:29.773     DEBUG     POST http://127.0.0.1:48802/hub/session/26f23ade-0f00-47bb-aaac-dd9ffc073dcd/elements {"using": "xpath", "sessionId": "26f23ade-0f00-47bb-aaac-dd9ffc073dcd", "value": "//title[text() = \"pev.com\"]"}     
11:07:29.778     DEBUG     Finished Request     
11:07:29.979     DEBUG     POST http://127.0.0.1:48802/hub/session/26f23ade-0f00-47bb-aaac-dd9ffc073dcd/elements {"using": "xpath", "sessionId": "26f23ade-0f00-47bb-aaac-dd9ffc073dcd", "value": "//title[text() = \"pev.com\"]"}     
11:07:29.987     DEBUG     Finished Request     
11:07:30.188     DEBUG     POST http://127.0.0.1:48802/hub/session/26f23ade-0f00-47bb-aaac-dd9ffc073dcd/elements {"using": "xpath", "sessionId": "26f23ade-0f00-47bb-aaac-dd9ffc073dcd", "value": "//title[text() = \"pev.com\"]"}     
11:07:30.193     DEBUG     Finished Request     
11:07:30.394     DEBUG     POST http://127.0.0.1:48802/hub/session/26f23ade-0f00-47bb-aaac-dd9ffc073dcd/elements {"using": "xpath", "sessionId": "26f23ade-0f00-47bb-aaac-dd9ffc073dcd", "value": "//title[text() = \"pev.com\"]"}     
11:07:30.401     DEBUG     Finished Request     
11:07:30.601     FAIL     Element '//title[text() = "pev.com"]' did not appear in 1 second     
11:07:30.601     DEBUG     Traceback (most recent call last):
  File "<decorator-gen-160>", line 2, in wait_until_page_contains_element
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 84, in wait_until_page_contains_element
    self._wait_until(timeout, error, self._is_element_present, locator)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 231, in _wait_until
    self._wait_until_no_error(timeout, wait_func)
  File "/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 240, in _wait_until_no_error
    raise AssertionError(timeout_error)     
11:04:24.658     TRACE     Arguments: [  ]     
11:04:24.657     TRACE     Arguments: [  ]     
```

**Comment by aaltat** [comment]
By defining the proper timeout value in the Wait\* keywords. See the [keyword documentation](http://robotframework.org/Selenium2Library/doc/Selenium2Library.html) timeouts chapter. Please note that all Wait\* keywords are polling type. Example if timeout is 60s but but the desired action happens in 5s, keyword will return after 5s. Timeout is only the maximum time for polling and if action does not happen within the timeout limit and error is raised and test execution is stopped.

**Comment by manycoding** [comment]
But I defined the timeout in the example above (Wait Until Page Contains Element //title[text() = "${SERVER}"], timeout=1), it's just Go To was executing 3 minutes while page was loading.

**Comment by aaltat** [comment]
Did you also try with `timeout\=5`, the backslash is intended?

**Comment by aaltat** [comment]
Did forget to add that the format should be only used with Create Webdriver keyword.

**Comment by manycoding** [comment]
I did, it doesn't change anything.

**Comment by ombre42** [comment]
I think the timeout passed via Create Webdriver is for sending commands to the server. Here the server is responding, but waiting indefinitely for a page load. To set the timeout for page load, you need to call `set_page_load_timeout` [doc](http://seleniumhq.github.io/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#selenium.webdriver.remote.webdriver.WebDriver.set_page_load_timeout). This is not exposed via S2L, but there are examples of getting a reference to the web driver instance and calling a method. I do not have a link handy.

**Comment by aaltat** [comment]
This is how you do it, in Python and Selenium side:

```
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.set_page_load_timeout(1)
driver.get('https://www.google.fi')
try:
    print 'Waiting input'
    WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.XPATH, '//input'))
        )
    print 'Input found'
finally:
    driver.quit()
```

You need to only replace the `driver.get('https://www.google.fi')` with correct url and `EC.presence_of_element_located((By.XPATH, '//input'))` with your xpath. Also remember to experiment with different `set_page_load_timeout` and `WebDriverWait(driver, 10).until(` values.

If you can get some combination of timeouts working: 
1. For a temporary solution, it is easy to turn that code to S2L extension keyword, which will open the browser with the correct timeout parameter. 
2. We (meaning maintainers of the S2L) need to discuss should we open the interface to the selenium timeout and if yes, in which way. 

If the `set_page_load_timeout` does not work, then the problem is on selenium side and issue should be taken to their side.

**Comment by manycoding** [comment]
Yep, `set_page_load_timeout` does it.
It throws `selenium.common.exceptions.TimeoutException` if the specified timeout is exceeded.

**Comment by aaltat** [comment]
Are you able to make the keyword by your self, or do you need help?

**Comment by manycoding** [comment]
I can do it myself, thanks for asking.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
