### ISSUE TITLE
TypeError 'not JSON serializable' when keyword added by 'Add Location Strategy' is called

### ISSUE THREAD

**Issue by divfor** [robotframework/SeleniumLibrary#542]
error msg:

```
[ ERROR ] Calling listener method 'start_keyword' of listener 'C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: TypeError: <selenium.webdriver.chrome.webdriver.WebDriver (session="e24401aad192ca16599c8da9241c6f56")> is not JSON serializable
[ ERROR ] Calling listener method 'end_keyword' of listener 'C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: TypeError: <selenium.webdriver.chrome.webdriver.WebDriver (session="e24401aad192ca16599c8da9241c6f56")> is not JSON serializable
```

trackback info:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 206, in _send_socket
    self.streamhandler.dump(packet)
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 430, in dump
    s = self._json_encoder(obj)
  File "C:\Python27\lib\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\Python27\lib\json\encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "C:\Python27\lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\Python27\lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\Python27\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Python27\lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\Python27\lib\json\encoder.py", line 442, in _iterencode
    o = _default(o)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <selenium.webdriver.chrome.webdriver.WebDriver (session="e24401aad192ca16599c8da9241c6f56")> is not JSON serializable
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 206, in _send_socket
    self.streamhandler.dump(packet)
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 430, in dump
    s = self._json_encoder(obj)
  File "C:\Python27\lib\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\Python27\lib\json\encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "C:\Python27\lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\Python27\lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\Python27\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Python27\lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\Python27\lib\json\encoder.py", line 442, in _iterencode
    o = _default(o)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <selenium.webdriver.chrome.webdriver.WebDriver (session="e24401aad192ca16599c8da9241c6f56")> is not JSON serializable
```

robotframework test case file:

``` robotframework
*** Settings ***
Library           Selenium2Library
Resource          define.txt

*** Test Cases ***
test Add Strategy
    [Setup]    Add Location Strategy    prompt_text    Map Baidu Main Page
    Open Browser    https://www.baidu.com    gc
    Click Element    prompt_text=hao123
    Sleep    1
    [Teardown]    Close Browser

*** Keywords ***
Map Baidu Main Page
    [Arguments]    ${browser}    ${criteria}    ${tag}    ${constraints}
    ${e}    Get Webelement    &{dict_main_page}[${criteria}]
    #${e}    Execute Javascript    return window.document.getElementById('${criteria}');
    [Return]    ${e}
```

resource file define.txt:

``` robotframework
*** Variables ***
&{dict_main_page}    hao123=css=#u1 > a:nth-child(3)
```

**Comment by aaltat** [comment]
Selenium2Library don't contain listeners and from stack trace can be seen that error is raised from RIDE. It seems that found a problem but raised the issue accidentally to wrong issue tracker. Could you write the issue in RIDE issue tracker.
