### ISSUE TITLE
robotframework Compatibility issue in win10

### ISSUE THREAD

**Issue by zyklonwu** [robotframework/SeleniumLibrary#553]
there are two issues appear in win10,as fallowing:

```
WebDriverException: Message: [object Object]'[object Object]' when calling method: [nsICommandProcessor::execute]
Stacktrace:
    at Dispatcher.executeAs/< (file:///c:/users/zyklon.wu/appdata/local/temp/tmpwr093g/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:9455)
    at Resource.prototype.handle (file:///c:/users/zyklon.wu/appdata/local/temp/tmpwr093g/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:9602)
    at Dispatcher.prototype.dispatch (file:///c:/users/zyklon.wu/appdata/local/temp/tmpwr093g/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:9549)
    at WebDriverServer/<.handle (file:///c:/users/zyklon.wu/appdata/local/temp/tmpwr093g/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:12390)
    at createHandlerFunc/< (file:///c:/users/zyklon.wu/appdata/local/temp/tmpwr093g/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:2054)
    at ServerHandler.prototype.handleResponse (file:///c:/users/zyklon.wu/appdata/local/temp/tmpwr093g/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:2387)
    at Connection.prototype.process (file:///c:/users/zyklon.wu/appdata/local/temp/tmpwr093g/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1223)
    at RequestReader.prototype._handleResponse (file:///c:/users/zyklon.wu/appdata/local/temp/tmpwr093g/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1677)
    at RequestReader.prototype._processBody (file:///c:/users/zyklon.wu/appdata/local/temp/tmpwr093g/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1525)
    at RequestReader.prototype.onInputStreamReady (file:///c:/users/zyklon.wu/appdata/local/temp/tmpwr093g/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1393)
```

2.sometimes robotframework-selenium2library's keyword didn't work,but there is no error

sorry ,my english is poor

**Comment by aaltat** [comment]
Could you share an example test case where this happens. Also could you share the full stack trace from the log and please use the `--loglevel trace` option when running the test case. Could you share more details from your environment: Python, browser, selenium and Selenium2Library versions.

**Comment by zyklonwu** [comment]
hi @aaltat ,thank you for your reply
python version:2.7.10
selenium version:2.48.0
Selenium2Library version:robotframework_selenium2library-1.7.4
browser:firefox 42 ,and forefox 24
PC:windows10

here is my script:

``` robotframework
    Open Browser    ${baseURL}
    Maximize Browser Window
    sleep    2
    wait until page contains element    xpath=//a[@class='pull-off-canvas js-pull-off-canvas']//i[@class='icon-account']
    Click Element    xpath=//a[@class='pull-off-canvas js-pull-off-canvas']//i[@class='icon-account']
    wait until page contains element    xpath=//*[@id='offCanvasLoginEmail']
    Input text    xpath=//*[@id='offCanvasLoginEmail']    ${accountna}
    Input Password    xpath=//*[@id='offCanvasLoginPassword']    ${passwd}
    Click Element    xpath=//*[@id='offCanvasLogin']
```

user login website when he click login button , it failed as fallowing:

```
20151218 09:37:34.500 :  INFO : Clicking element 'xpath=//*[@id='offCanvasLogin']'.
20151218 09:37:34.500 : DEBUG : POST http://127.0.0.1:65236/hub/session/ae60caa9-e69f-4b64-8e02-3f0ab0599220/elements {"using": "xpath", "sessionId": "ae60caa9-e69f-4b64-8e02-3f0ab0599220", "value": "//*[@id='offCanvasLogin']"}
20151218 09:37:34.560 : DEBUG : Finished Request
20151218 09:37:34.564 : TRACE : Arguments: [  ]
20151218 09:37:34.568 : DEBUG : GET http://127.0.0.1:65236/hub/session/ae60caa9-e69f-4b64-8e02-3f0ab0599220/screenshot {"sessionId": "ae60caa9-e69f-4b64-8e02-3f0ab0599220"}
20151218 09:37:38.279 : DEBUG : Finished Request
20151218 09:37:38.311 :  INFO : </td></tr><tr><td colspan="3"><a href="selenium-screenshot-1.png"><img src="selenium-screenshot-1.png" width="800px"></a>
20151218 09:37:38.312 : TRACE : Return: None
20151218 09:37:38.319 :  FAIL : 
WebDriverException: Message: [object Object]'[object Object]' when calling method: [nsICommandProcessor::execute]
Stacktrace:
    at Dispatcher.executeAs/< (file:///c:/users/zyklon.wu/appdata/local/temp/tmpunyuky/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:9455)
    at Resource.prototype.handle (file:///c:/users/zyklon.wu/appdata/local/temp/tmpunyuky/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:9602)
    at Dispatcher.prototype.dispatch (file:///c:/users/zyklon.wu/appdata/local/temp/tmpunyuky/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:9549)
    at WebDriverServer/<.handle (file:///c:/users/zyklon.wu/appdata/local/temp/tmpunyuky/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:12390)
    at createHandlerFunc/< (file:///c:/users/zyklon.wu/appdata/local/temp/tmpunyuky/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:2054)
    at ServerHandler.prototype.handleResponse (file:///c:/users/zyklon.wu/appdata/local/temp/tmpunyuky/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:2387)
    at Connection.prototype.process (file:///c:/users/zyklon.wu/appdata/local/temp/tmpunyuky/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1223)
    at RequestReader.prototype._handleResponse (file:///c:/users/zyklon.wu/appdata/local/temp/tmpunyuky/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1677)
    at RequestReader.prototype._processBody (file:///c:/users/zyklon.wu/appdata/local/temp/tmpunyuky/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1525)
    at RequestReader.prototype.onInputStreamReady (file:///c:/users/zyklon.wu/appdata/local/temp/tmpunyuky/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1393)
20151218 09:37:38.320 : DEBUG : 
Traceback (most recent call last):
  File "<decorator-gen-46>", line 2, in click_element
  File "C:\Python27\Lib\site-packages\Selenium2Library\keywords\keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\Selenium2Library\keywords\_element.py", line 344, in click_element
    self._element_find(locator, True, True).click()
  File "C:\Python27\Lib\site-packages\Selenium2Library\keywords\_element.py", line 678, in _element_find
    elements = self._element_finder.find(browser, locator, tag)
  File "C:\Python27\Lib\site-packages\Selenium2Library\locators\elementfinder.py", line 37, in find
    return strategy(browser, criteria, tag, constraints)
  File "C:\Python27\Lib\site-packages\Selenium2Library\locators\elementfinder.py", line 79, in _find_by_xpath
    browser.find_elements_by_xpath(criteria),
  File "C:\Python27\lib\site-packages\selenium-2.48.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 270, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium-2.48.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 739, in find_elements
    {'using': by, 'value': value})['value']
  File "C:\Python27\Lib\site-packages\Selenium2Library\webdrivermonkeypatches.py", line 11, in execute
    result = self._base_execute(driver_command, params)
  File "C:\Python27\lib\site-packages\selenium-2.48.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium-2.48.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
```

**Comment by aaltat** [comment]
I don't see any problems in your test data. Also I do not see errors, which could be explained by a dynamic content in the page. But it doesn't mean that I am right in my assumption, because dynamic content may lead to strange errors. But the Firefox 42 version is quite new and it's very common that Firefox upgrade break's the selenium comparability. Have you tried with older versions of Firefox, if I recall correctly 38 is the latest supported version from selenium side. Also trying with Chrome would be good idea too.

**Comment by zyklonwu** [comment]
@aaltat ，thank you for your reply
i have installed firefox 38.5 ESR

it appeared the same issue

```
20151218 16:06:20.611 : DEBUG : Opened browser with session id 24eb0557-fe32-4eb7-8861-e602d0fa5030
20151218 16:06:20.611 : TRACE : Return: 1
20151218 16:06:20.612 : TRACE : Arguments: [  ]
20151218 16:06:20.613 : DEBUG : POST http://127.0.0.1:56447/hub/session/24eb0557-fe32-4eb7-8861-e602d0fa5030/window/current/maximize {"windowHandle": "current", "sessionId": "24eb0557-fe32-4eb7-8861-e602d0fa5030"}
20151218 16:06:20.785 : DEBUG : Finished Request
20151218 16:06:20.785 : TRACE : Return: None
20151218 16:06:20.787 : TRACE : Arguments: [ '2' ]
20151218 16:06:22.787 :  INFO : Slept 2 seconds
20151218 16:06:22.788 : TRACE : Return: None
20151218 16:06:22.789 : TRACE : Arguments: [ "xpath=//a[@class='pull-off-canvas js-pull-off-canvas']//i[@class='icon-account']" ]
20151218 16:06:22.789 : DEBUG : POST http://127.0.0.1:56447/hub/session/24eb0557-fe32-4eb7-8861-e602d0fa5030/elements {"using": "xpath", "sessionId": "24eb0557-fe32-4eb7-8861-e602d0fa5030", "value": "//a[@class='pull-off-canvas js-pull-off-canvas']//i[@class='icon-account']"}
20151218 16:06:22.891 : DEBUG : Finished Request
20151218 16:06:22.892 : TRACE : Return: None
20151218 16:06:22.894 : TRACE : Arguments: [ "xpath=//a[@class='pull-off-canvas js-pull-off-canvas']//i[@class='icon-account']" ]
20151218 16:06:22.894 :  INFO : Clicking element 'xpath=//a[@class='pull-off-canvas js-pull-off-canvas']//i[@class='icon-account']'.
20151218 16:06:22.895 : DEBUG : POST http://127.0.0.1:56447/hub/session/24eb0557-fe32-4eb7-8861-e602d0fa5030/elements {"using": "xpath", "sessionId": "24eb0557-fe32-4eb7-8861-e602d0fa5030", "value": "//a[@class='pull-off-canvas js-pull-off-canvas']//i[@class='icon-account']"}
20151218 16:06:22.932 : DEBUG : Finished Request
20151218 16:06:22.933 : DEBUG : POST http://127.0.0.1:56447/hub/session/24eb0557-fe32-4eb7-8861-e602d0fa5030/element/{59fc08a1-a510-4ed0-b696-104d0e15fc54}/click {"sessionId": "24eb0557-fe32-4eb7-8861-e602d0fa5030", "id": "{59fc08a1-a510-4ed0-b696-104d0e15fc54}"}
20151218 16:06:22.988 : DEBUG : Finished Request
20151218 16:06:22.990 : TRACE : Arguments: [  ]
20151218 16:06:22.994 : DEBUG : GET http://127.0.0.1:56447/hub/session/24eb0557-fe32-4eb7-8861-e602d0fa5030/screenshot {"sessionId": "24eb0557-fe32-4eb7-8861-e602d0fa5030"}
20151218 16:06:27.096 : DEBUG : Finished Request
20151218 16:06:27.143 :  INFO : </td></tr><tr><td colspan="3"><a href="selenium-screenshot-1.png"><img src="selenium-screenshot-1.png" width="800px"></a>
20151218 16:06:27.146 : TRACE : Return: None
20151218 16:06:27.151 :  FAIL : 
WebDriverException: Message: [object Object]'[object Object]' when calling method: [nsICommandProcessor::execute]
Stacktrace:
    at Dispatcher.executeAs/< (file:///c:/users/zyklon.wu/appdata/local/temp/tmpsafswb/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:9456)
    at Resource.prototype.handle (file:///c:/users/zyklon.wu/appdata/local/temp/tmpsafswb/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:9603)
    at Dispatcher.prototype.dispatch (file:///c:/users/zyklon.wu/appdata/local/temp/tmpsafswb/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:9550)
    at WebDriverServer/<.handle (file:///c:/users/zyklon.wu/appdata/local/temp/tmpsafswb/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/driver-component.js:12497)
    at createHandlerFunc/< (file:///c:/users/zyklon.wu/appdata/local/temp/tmpsafswb/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:2054)
    at ServerHandler.prototype.handleResponse (file:///c:/users/zyklon.wu/appdata/local/temp/tmpsafswb/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:2387)
    at Connection.prototype.process (file:///c:/users/zyklon.wu/appdata/local/temp/tmpsafswb/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1223)
    at RequestReader.prototype._handleResponse (file:///c:/users/zyklon.wu/appdata/local/temp/tmpsafswb/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1677)
    at RequestReader.prototype._processBody (file:///c:/users/zyklon.wu/appdata/local/temp/tmpsafswb/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1525)
    at RequestReader.prototype.onInputStreamReady (file:///c:/users/zyklon.wu/appdata/local/temp/tmpsafswb/webdriver-py-profilecopy/extensions/fxdriver@googlecode.com/components/httpd.js:1393)
20151218 16:06:27.151 : DEBUG : 
Traceback (most recent call last):
  File "<decorator-gen-46>", line 2, in click_element
  File "C:\Python27\Lib\site-packages\Selenium2Library\keywords\keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\Selenium2Library\keywords\_element.py", line 344, in click_element
    self._element_find(locator, True, True).click()
  File "C:\Python27\lib\site-packages\selenium-2.47.1-py2.7.egg\selenium\webdriver\remote\webelement.py", line 69, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium-2.47.1-py2.7.egg\selenium\webdriver\remote\webelement.py", line 448, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\Lib\site-packages\Selenium2Library\webdrivermonkeypatches.py", line 11, in execute
    result = self._base_execute(driver_command, params)
  File "C:\Python27\lib\site-packages\selenium-2.47.1-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 196, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium-2.47.1-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
============================================================
and i also used chrome(version 46) to run this testcase,it had another issue as fallowing:
20151218 16:21:37.061 : TRACE : Arguments: [ "xpath=//div[@class='container-infinite']//nav[@class='nav']//ul[@class='list-inline']" ]
20151218 16:21:37.062 :  INFO : Clicking element 'xpath=//div[@class='container-infinite']//nav[@class='nav']//ul[@class='list-inline']'.
20151218 16:21:37.063 : DEBUG : POST http://127.0.0.1:56856/session/647e525157b55c565902922cecd97d34/elements {"using": "xpath", "sessionId": "647e525157b55c565902922cecd97d34", "value": "//div[@class='container-infinite']//nav[@class='nav']//ul[@class='list-inline']"}
20151218 16:21:37.090 : DEBUG : Finished Request
20151218 16:21:37.091 : DEBUG : POST http://127.0.0.1:56856/session/647e525157b55c565902922cecd97d34/element/0.8901056700851768-6/click {"sessionId": "647e525157b55c565902922cecd97d34", "id": "0.8901056700851768-6"}
20151218 16:21:37.143 : DEBUG : Finished Request
20151218 16:21:37.144 : TRACE : Arguments: [  ]
20151218 16:21:37.147 : DEBUG : GET http://127.0.0.1:56856/session/647e525157b55c565902922cecd97d34/screenshot {"sessionId": "647e525157b55c565902922cecd97d34"}
20151218 16:21:37.841 : DEBUG : Finished Request
20151218 16:21:37.853 :  INFO : </td></tr><tr><td colspan="3"><a href="selenium-screenshot-1.png"><img src="selenium-screenshot-1.png" width="800px"></a>
20151218 16:21:37.854 : TRACE : Return: None
20151218 16:21:37.860 :  FAIL : 
WebDriverException: Message: unknown error: Element is not clickable at point (951, 70). Other element would receive the click: <div class="exit-off-canvas js-exit-off-canvas"></div>
  (Session info: chrome=46.0.2490.86)
  (Driver info: chromedriver=2.19.346078 (6f1f0cde889532d48ce8242342d0b84f94b114a1),platform=Windows NT 10.0 x86_64)

20151218 16:21:37.863 : DEBUG : 
Traceback (most recent call last):
  File "<decorator-gen-46>", line 2, in click_element
  File "C:\Python27\Lib\site-packages\Selenium2Library\keywords\keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\Selenium2Library\keywords\_element.py", line 344, in click_element
    self._element_find(locator, True, True).click()
  File "C:\Python27\lib\site-packages\selenium-2.47.1-py2.7.egg\selenium\webdriver\remote\webelement.py", line 69, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium-2.47.1-py2.7.egg\selenium\webdriver\remote\webelement.py", line 448, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\Lib\site-packages\Selenium2Library\webdrivermonkeypatches.py", line 11, in execute
    result = self._base_execute(driver_command, params)
  File "C:\Python27\lib\site-packages\selenium-2.47.1-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 196, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium-2.47.1-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
```

**Comment by aaltat** [comment]
What about chrome?

**Comment by aaltat** [comment]
Sorry there was chrome error too

**Comment by aaltat** [comment]
In Firefox error is unclear but on Chrome the error is clearer: `WebDriverException: Message: unknown error: Element is not clickable at point (951, 70). Other element would receive the click`

Which means that selenium refuses to perform the click because other element would receive the click. There are many reasons why it could happen, one of the most common, in my experience, is that the selector is not unique. Somewhere in DOM, is other element, which also matches to the selector but that element is hidden or under some other element. I use Firebug and Firepath tools to create the selector and make sure that they are unique.

**Comment by aaltat** [comment]
Because this seems to be a problem in how the library is used and not in library it self, I was planning to close the issue. But before issue is closed, do you have an update that would provide evidence that this is an issue in the Selenium2Library and the issue should remain open?

**Comment by aaltat** [comment]
Closed because this is not issue in the library.
