### ISSUE TITLE
test failed due to web driver change

### ISSUE THREAD

**Issue by divfor** [robotframework/SeleniumLibrary#594]
recently I found all PR failed to pass CI checking. the tests fail on 'Unselect From List' that calls WebDriver's select.dselect_by_value() which will throw "NoSuchElementException".

we need to fix the test cases in lists.robot.

```
12:41:20.660    FAIL    NoSuchElementException: Message: Could not locate element with value: Tin Can Phone
12:41:20.661    DEBUG   Traceback (most recent call last):
  File "<decorator-gen-134>", line 2, in unselect_from_list
  File "/home/fred/Downloads/robotframework-selenium2library-Enhance-Location-Strategy/src/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/home/fred/Downloads/robotframework-selenium2library-Enhance-Location-Strategy/src/Selenium2Library/keywords/_selectelement.py", line 274, in unselect_from_list
    select.deselect_by_value(item)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/select.py", line 170, in deselect_by_value
    raise NoSuchElementException("Could not locate element with value: %s" % value)
```

**Comment by divfor** [comment]
#597 for solutuion

**Comment by aaltat** [comment]
Can this be closed?
