### ISSUE TITLE
FAIL : OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by nam-edi** [robotframework/SeleniumLibrary#595]
Hi guys, 

I installed Selenium2Library on MacOS and when I want to just open a browser is what I like error:

``````
20160419 16:00:04.526 :  FAIL : OSError: [Errno 2] No such file or directory
20160419 16:00:04.526 : DEBUG : 
Traceback (most recent call last):
  File "<decorator-gen-88>", line 2, in open_browser
  File "/Library/Python/2.7/site-packages/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 114, in open_browser
    browser = self._make_browser(browser_name,desired_capabilities,ff_profile_dir,remote_url)
  File "/Library/Python/2.7/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 528, in _make_browser
    browser = creation_func(remote, desired_capabilities, profile_dir)
  File "/Library/Python/2.7/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 544, in _make_ff
    browser = webdriver.Firefox(firefox_profile=profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 103, in __init__
    self.binary, timeout)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, err write
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception

```)
I tried to uninstall and reinstall the library but it does not change.

robotframework-selenium2library==1.7.4
decorator==4.0.9

Thx
``````

**Comment by aaltat** [comment]
Without looking the source code of the selenium, I would guess that your Firefox installation is not found. Do you have Firefox installed and is it installed in the default location? Selenium is actually quite picky on the installation location.

**Comment by aaltat** [comment]
Oh and could you tell the selenium version too?

**Comment by nam-edi** [comment]
I am ashamed .... Sorry, it was not installed, to force change pc I am lost.

**Comment by aaltat** [comment]
No worries, it is good that you found the reason for the error. Closing the issue because it looks like it was resolved.
