### ISSUE TITLE
Calling method 'report_file' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053]

### ISSUE THREAD

**Issue by jokerbo1** [robotframework/SeleniumLibrary#603]
Hello , i have a question ,i wang to solution the problem, i will run the robotframework-ride ,the browser is firefox ,but the browser is too long of the response time,so throw the execption  ,follow this:

[ ERROR ] Calling method 'log_message' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'log_message' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'end_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'log_message' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'log_message' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'end_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'log_message' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'end_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'start_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'end_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'end_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'start_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'start_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
    self.filehandler.flush()
  File "D:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
    self.filehandler.flush()
  File "D:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
    self.filehandler.flush()
  File "D:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
    self.filehandler.flush()
  File "D:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
    self.filehandler.flush()
  File "D:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
    self.filehandler.flush()
  File "D:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
    self.filehandler.flush()
  File "D:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
    self.filehandler.flush()
  File "D:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053]

**Comment by aaltat** [comment]
Unfortunately the RIDE is not the most stable editor, although it is very good editor for Robot Framework. As a workaround, you could restart RIDE and problem should go away, for temporally at least. For a more permanent solution, you could run the test case(s) from [command line](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id141). 

But this is RIDE problem and not a Selenium2Library issue, because all the stack traces are from RIDE,. Therefore I am closing the issue. You could report the issue the [RIDE issue](https://github.com/robotframework/RIDE/issues) tracker and which you have already [done](https://github.com/robotframework/RIDE/issues/1634).
