### ISSUE TITLE
Try out the selenium 3 beta

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#644]
Try the selenium 3.0 and see does it bring any problems.
- [x] Firefox works
- [x] Chrome works
- [x] IE works
- [x] Edge works
- [x] Safari wirks

**Comment by aaltat** [comment]
Firefox needs gecko driver. This error is seen when running with FF: `WebDriverException: Message: 'geckodriver' executable needs to be in PATH.`

**Comment by aaltat** [comment]
On chrome the results looks better. Out of 249, 143 did pass. The reason for so many failures is that the Alert test failed and did cause bunch of other test to fail too. The Alert problem needs more investigation, here is the stack trace: 

```
23:29:22.300    FAIL    There were no alerts    
23:29:22.300    DEBUG   Traceback (most recent call last):
  File "<decorator-gen-158>", line 2, in alert_should_be_present
  File "/home/godtdd/workspace/robotframework-selenium2library/src/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/home/godtdd/workspace/robotframework-selenium2library/src/Selenium2Library/keywords/_alert.py", line 33, in alert_should_be_present
    alert_text = self.get_alert_message()
  File "<decorator-gen-159>", line 2, in get_alert_message
  File "/home/godtdd/workspace/robotframework-selenium2library/src/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/home/godtdd/workspace/robotframework-selenium2library/src/Selenium2Library/keywords/_alert.py", line 90, in get_alert_message
    return self._close_alert()
  File "/home/godtdd/workspace/robotframework-selenium2library/src/Selenium2Library/keywords/_alert.py", line 108, in _close_alert
    self._handle_alert(confirm)
  File "/home/godtdd/workspace/robotframework-selenium2library/src/Selenium2Library/keywords/_alert.py", line 132, in _handle_alert
    raise RuntimeError('There were no alerts')  
00:00:00.017 
```

**Comment by aaltat** [comment]
There is also problem using selenium 2.x with chrome alerts: #652. It could be that alert problem is not caused by selenium 3. 

But the Firefox needs some work.

**Comment by aaltat** [comment]
The selenium 3 is drop in replacement for selenium 2. There are some problems with Firefox 48 or greater and selenium 3. But that has a separate issue. Closing this issue
