### ISSUE TITLE
"Mouse Out"and  "Press Key" acceptance test failed

### ISSUE THREAD

**Issue by jollychang** [robotframework/SeleniumLibrary#69]
``` shell
#Firefox 10.0.2
cd test && run_tests.py python ff
```
### Mouse Out

``` html
Documentation:  
Verifies the value in text field identified by `locator` is exactly `expected`.
Start / End / Elapsed:  20120625 15:14:57.896 / 20120625 15:14:57.915 / 00:00:00.019
15:14:57.898    DEBUG   GET http://127.0.0.1:58434/hub/session/cb4018b6-160c-6d45-bb09-433c11f8f179/url {"sessionId": "cb4018b6-160c-6d45-bb09-433c11f8f179"}
15:14:57.903    DEBUG   POST http://127.0.0.1:58434/hub/session/cb4018b6-160c-6d45-bb09-433c11f8f179/elements {"using": "xpath", "sessionId": "cb4018b6-160c-6d45-bb09-433c11f8f179", "value": "//input[@type='text' and (@id='el_for_mouseout' or @name='el_for_mouseout' or @value='el_for_mouseout' or @src='el_for_mouseout' or @src='http://localhost:7000/html/mouse/el_for_mouseout')]"}
15:14:57.909    DEBUG   GET http://127.0.0.1:58434/hub/session/cb4018b6-160c-6d45-bb09-433c11f8f179/element/{556a6780-d460-1948-aabe-9617e66d7706}/attribute/value {"sessionId": "cb4018b6-160c-6d45-bb09-433c11f8f179", "name": "value", "id": "{556a6780-d460-1948-aabe-9617e66d7706}"}
15:14:57.915    FAIL    Value of text field 'el_for_mouseout' should have been 'mouseout el_for_mouseout' but was ''
15:14:57.915    DEBUG   Traceback (most recent call last):
  File "<string>", line 2, in textfield_value_should_be
  File "/Users/jollychang/Works/robotframework-selenium2library/src/Selenium2Library/keywords/keywordgroup.py", line 12, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/Users/jollychang/Works/robotframework-selenium2library/src/Selenium2Library/keywords/_formelement.py", line 253, in textfield_value_should_be
    raise AssertionError(message)
```
### Press Key

``` html
KEYWORD: Selenium2Library.Location Should Be ${ROOT}/${relative url} Expand All
Documentation:  
Verifies that current URL is exactly `url`.
Start / End / Elapsed:  20120625 15:15:50.036 / 20120625 15:15:50.067 / 00:00:00.031
15:15:50.037    DEBUG   GET http://127.0.0.1:58434/hub/session/cb4018b6-160c-6d45-bb09-433c11f8f179/url {"sessionId": "cb4018b6-160c-6d45-bb09-433c11f8f179"}
15:15:50.067    FAIL    Location should have been 'http://localhost:7000/html/forms/submit.html' but was 'http://localhost:7000/html/forms/login.html'
15:15:50.067    DEBUG   Traceback (most recent call last):
  File "<string>", line 2, in location_should_be
  File "/Users/jollychang/Works/robotframework-selenium2library/src/Selenium2Library/keywords/keywordgroup.py", line 12, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/Users/jollychang/Works/robotframework-selenium2library/src/Selenium2Library/keywords/_browsermanagement.py", line 231, in location_should_be
    % (url, actual))

```

create a travis-ci project is good idea?

**Comment by emanlove** [comment]
Looking at the specs for [Travis CI](http://about.travis-ci.org/) (i.e. OSes, Browsers, Build Configurations), I think something like [ShiningPanda](https://www.shiningpanda.com/) is more focused on our testing needs and specifications.  But, yes, having a CI server would be helpful and a good idea.

**Comment by emanlove** [comment]
"Mouse Out" and "Press Key" are working with the latest version of Selenium2Libary.  The Robot Framework Team has graciously allowed us to add Selenium2Library tests to [their Jenkins CI server](http://robot.radiaatto.ri.fi). In addition I will add a basic Travis CI configuration to the project which will provide a first line of defence in terms of potential issues with pull requests (under limited system configurations).
