### ISSUE TITLE
Element Not Found raises exception with Safari

### ISSUE THREAD

**Issue by serhatbolsu** [robotframework/SeleniumLibrary#700]
For Safari, 
`Wait until element is not visible` throws element not found exception. It seems like handling a element not found automatically raise exception.
Same applies for all find element functions so in practice "Safari" is broken

POST http://127.0.0.1:63517/session/2DB73404-082E-49A0-9DC7-BC80A32EF1FE/elements {"using": "css selector", "sessionId": "2DB73404-082E-49A0-9DC7-BC80A32EF1FE", "value": "body.page-loading"}	
18:17:59.951	DEBUG	Finished Request	
18:18:00.337	FAIL	NoSuchElementException: Message: An element could not be located on the page using the given search parameters.
18:18:00.338	DEBUG	Traceback (most recent call last):
  File "<decorator-gen-148>", line 2, in wait_until_element_is_not_visible
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 151, in wait_until_element_is_not_visible
    self._wait_until_no_error(timeout, check_hidden)
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 237, in _wait_until_no_error
    timeout_error = wait_func(*args)
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/Selenium2Library/keywords/_waiting.py", line 144, in check_hidden
    visible = self._is_visible(locator)
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/Selenium2Library/keywords/_element.py", line 735, in _is_visible
    element = self._element_find(locator, True, False)
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/Selenium2Library/keywords/_element.py", line 688, in _element_find
    elements = self._element_finder.find(browser, locator, tag)
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/Selenium2Library/locators/elementfinder.py", line 37, in find
    return strategy(browser, criteria, tag, constraints)
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/Selenium2Library/locators/elementfinder.py", line 108, in _find_by_css_selector
    browser.find_elements_by_css_selector(criteria),
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 449, in find_elements_by_css_selector
    return self.find_elements(by=By.CSS_SELECTOR, value=css_selector)
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 778, in find_elements
    'value': value})['value']
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/Selenium2Library/webdrivermonkeypatches.py", line 11, in execute
    result = self._base_execute(driver_command, params)
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/serhatbolsu/Aliza/aliza-projects/venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)

**Comment by aaltat** [comment]
Would it be possible to run the same test by using different browser, example Chrome. This will tell is this browser specific problem or a common problem. Also could you tell which Selenium2Library and selenium version you are using?

**Comment by serhatbolsu** [comment]
I ran on Chrome or IE10-11 without problem. It seems like whole Safari execution became in practicle since it does fail on first not found element (`wait until page contains element` also does not work)

I am using a Safari 10.1 in El Capitan and the library version is 1.8.0, selenium 3.0.2
Thank you

**Comment by aaltat** [comment]
Also could you tell which Selenium2Library and selenium version you are using?

**Comment by aaltat** [comment]
Ah sorry did miss read your last post, the information is there

**Comment by aaltat** [comment]
Have you tried with latest selenium 2.x version?

If I recall the code correctly, it uses find_elements_by* methods from selenium. Those methods should not never raise exceptions. They should always return list of elements, empty list if nothing is found.

Either this is a bug in the selenium side, with the version you are using. Or something has changed in the selenium API with the selenium 3. If the test work with selenium 2, it's most likely problem with selenium.

**Comment by serhatbolsu** [comment]
I beleive what you saying is correct that it would work with selenium older. However now Safari is like Chromium, and it is handled by its own team.

And this is not their first release so I guess, Selenium2Library  will need to follow up this change.

**Comment by aaltat** [comment]
Did the selenium 2.x release solve the problem?

The selenium provides a unified API to the different browser and the API methods works in same way in all different browser. Also in our side, excluding the Open Browser keyword related code, Selenium2Library does not contain any browser specific code, as far I recall. Also we are not going to build browser specific code in to the library.

Because in your case, the selenium API is working differently for different browser, it strongly looks like a bug in the selenium side. Therefore it would be best to report the problem to the selenium user group.

**Comment by serhatbolsu** [comment]
I found that it is about Safari 10 and its related webdriver ( new driver).

The thing is I believe this is the way they will handle not found items, so client(selenium2library) might have to handle exceptions as well.

**Comment by aaltat** [comment]
Your assumption is not correct. But I think is a bug in the selenium side and you could open a issue in their issue tracker.

**Comment by aaltat** [comment]
Because this looks like it's not a problem in the S2L and looks like a problem selenium or the Safari driver implementation, I am closing the issue.
