### ISSUE TITLE
Run Tests Fails in window

### ISSUE THREAD

**Issue by vairamsvsjdo** [robotframework/SeleniumLibrary#786]
Installed selenium2library version 
Robot Framework 3.0.3.dev20170213 (Python 2.7.12 on win32)
Firefox - 52.0.2 (32-bit)
Selenium GeckoDriver v0.15 (https://github.com/mozilla/geckodriver/releases)
robotframework-selenium2library==1.7.4

c:\rfs2lib>python test/run_tests.py python firefox
Running unit tests
..................E..E..............................................................................EEE....
======================================================================
ERROR: test_create_webdriver (unit.keywords.test_browsermanagement.BrowserManagementTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\rfs2lib\test\unit\keywords\test_browsermanagement.py", line 116, in test_create_webdriver
    self.assertEquals(capt_data['webdriver'], bm._current_browser())
  File "c:\rfs2lib\test\..\src\Selenium2Library\keywords\_browsermanagement.py", line 515, in _current_browser
    if not self._cache.current:
  File "C:\Python27\lib\site-packages\future-0.16.0-py2.7.egg\future\types\newobject.py", line 88, in __nonzero__
    return type(self).__bool__(self)
AttributeError: type object 'FakeWebDriver' has no attribute '__bool__'

======================================================================
ERROR: test_set_selenium_timeout_only_affects_open_browsers (unit.keywords.test_browsermanagement.BrowserManagementTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\rfs2lib\test\unit\keywords\test_browsermanagement.py", line 85, in test_set_selenium_timeout_only_affects_open_browsers
    bm._cache.close()
  File "c:\rfs2lib\test\..\src\Selenium2Library\utils\browsercache.py", line 21, in close
    if self.current:
  File "C:\Python27\lib\site-packages\future-0.16.0-py2.7.egg\future\types\newobject.py", line 88, in __nonzero__
    return type(self).__bool__(self)
AttributeError: type object 'mock' has no attribute '__bool__'

======================================================================
ERROR: test_close (unit.utils.test_browsercache.BrowserCacheTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\rfs2lib\test\unit\utils\test_browsercache.py", line 60, in test_close
    cache.close()
  File "c:\rfs2lib\test\..\src\Selenium2Library\utils\browsercache.py", line 21, in close
    if self.current:
  File "C:\Python27\lib\site-packages\future-0.16.0-py2.7.egg\future\types\newobject.py", line 88, in __nonzero__
    return type(self).__bool__(self)
AttributeError: type object 'mock' has no attribute '__bool__'

======================================================================
ERROR: test_close_only_called_once (unit.utils.test_browsercache.BrowserCacheTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\rfs2lib\test\unit\utils\test_browsercache.py", line 74, in test_close_only_called_once
    cache.close()
  File "c:\rfs2lib\test\..\src\Selenium2Library\utils\browsercache.py", line 21, in close
    if self.current:
  File "C:\Python27\lib\site-packages\future-0.16.0-py2.7.egg\future\types\newobject.py", line 88, in __nonzero__
    return type(self).__bool__(self)
AttributeError: type object 'mock' has no attribute '__bool__'

======================================================================
ERROR: test_get_open_browsers (unit.utils.test_browsercache.BrowserCacheTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\rfs2lib\test\unit\utils\test_browsercache.py", line 48, in test_get_open_browsers
    cache.close()
  File "c:\rfs2lib\test\..\src\Selenium2Library\utils\browsercache.py", line 21, in close
    if self.current:
  File "C:\Python27\lib\site-packages\future-0.16.0-py2.7.egg\future\types\newobject.py", line 88, in __nonzero__
    return type(self).__bool__(self)
AttributeError: type object 'mock' has no attribute '__bool__'

----------------------------------------------------------------------
Ran 107 tests in 0.062s

FAILED (errors=5)

5 unit tests failed - not running acceptance tests!

c:\rfs2lib>

**Comment by aaltat** [comment]
Would you mind using the latest (1.8.0) Selenium2Library version.

**Comment by aaltat** [comment]
Where you able to try with the latest released version? Also it would be better if you would be able to try with master from the repository because there is fix for the test server in #780

**Comment by aaltat** [comment]
Can not reproduce the problem. Also closing due inactivity. IF you feel that this is still a problem, send and update and we will see should the issue be opened.

**Comment by vairamsvsjdo** [comment]
Still got the same error

pip list robotframework =>
appdirs (1.4.3)
decorator (4.0.11)
docutils (0.13.1)
future (0.16.0)
packaging (16.8)
pip (9.0.1)
pyparsing (2.2.0)
robotframework (3.0.3.dev20170213)
robotframework-selenium2library (1.8.0)
selenium (3.3.3)
setuptools (34.4.1)
six (1.10.0)

**Comment by vairamsvsjdo** [comment]
tried with robotframework 3.0.2 as well

**Comment by aaltat** [comment]
And if you take the latest source from the master, does it then work?

Also could you try downgrade the  future to version 0.15.x and give it a try?

**Comment by aaltat** [comment]
Did you have any progress on the matter?

**Comment by aaltat** [comment]
Closing due inactivity. If you think that you have a problem, send an update.
